### ISSUE TITLE
Default buildkite bootstrap fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by lox** [buildkite/feedback#100]
After an installation via APT on Ubuntu 15.04, I get the following error in my builds:

```
/usr/share/buildkite-agent/bootstrap.sh: line 194: HOME: unbound variable
```

After adding a `Environment=HOME=/root` line to the systemd unit file, things worked again.

**Comment by keithpitt** [comment]
Thanks for this @lox! I've moved the issue to here: https://github.com/buildkite/agent/issues/162

**Comment by keithpitt** [comment]
I just tried to replicate this @lox on a fresh Ubuntu 15 machine installed on Digital Ocean, and I didn't get the error. Were you doing any docker stuff at the time?

**Comment by Phantazm** [comment]
Same issue on Debian 8

**Comment by keithpitt** [comment]
@Phantazm using systemd?

**Comment by Phantazm** [comment]
Correct, i just quick fixed it by adding:
```HOME=/root``` in ```Project Environment Variables``` within buildkite build setup.
