### ISSUE TITLE
API vs Doc inconsistency

### ISSUE THREAD

**Issue by byroot** [buildkite/feedback#102]
The API documentation says agents meta data are key value pairs:

```json
"meta_data": [["key","val"]]
```

But when I query it I get them as an array of strings:
```json
"meta_data": ["mac=true", "retail=true"]
```

**Comment by toolmantim** [comment]
Sorry about that! That might have been wishful thinking, as I think the array version is probably easier to deal with.

I've updated the docs with the correct, string version: https://buildkite.com/docs/api/agents

Thanks for the bug report! :+1: :bug:

**Comment by byroot** [comment]
No problem. Thanks!
