### ISSUE TITLE
Timeout "stopping" agents without jobs

### ISSUE THREAD

**Issue by toolmantim** [buildkite/feedback#104]
If an agent is gracefully stopped and doesn't manage to report back, it stays stuck as `stopping`. If it doesn't have a job assigned it'd be nice to simply time it out after `x` minutes so manual cleanup is only needed for ones that were executing jobs.

**Comment by keithpitt** [comment]
Yup, I agree.

**Comment by keithpitt** [comment]
This has been :ship:'d!! :dash:
