### ISSUE TITLE
Provide test results for individual scenarios/examples 

### ISSUE THREAD

**Issue by patrobinson** [buildkite/feedback#107]
It would be useful to report on individual scenario/example historical stats to look for flakey tests etc. Similar functionality is provided in Bamboo/Jenkins by specifying a structured output formatter for say rspec and parsing that output.

**Comment by keithpitt** [comment]
We've been thinking about this for a while, we haven't figured out how to communicate the failures back to Buildkite yet - once we've figured that out - we should be able to do something like this!

**Comment by nemski** [comment]
You already get the log output back to buildkite in raw format. You can also specify say rspec_junit_formatter as the output and transport the files back. This can then be used to render results instead of raw output, so you can see test groups and expand to see individual failures instead of scrolling. Then you'll have each test and it's result which can be stored for historical purposes

**Comment by nemski** [comment]
Although the solution is obviously different for each testing framework

**Comment by KJTsanaktsidis** [comment]
This is something that we do with Bamboo at the moment; we use the rspec_junit_formatter and Bamboo can give us a list of which tests failed & what build they started failing on. I'm evaluating Buildkite for my organisation at the moment and this is definitely a feature we currently use a lot.

**Comment by amcdnl** [comment]
Ya, we use this feature in Bamboo too. We have looked at CodeClimate for this but curious if you guys are planning to fill this gap.

**Comment by sj26** [comment]
#196 is also kinda related :-)

**Comment by mdub** [comment]
FWIW, one of my users has also wished for better insight into unit-test results, after migrating from Bamboo to Buildkite.

**Comment by keithpitt** [comment]
👋 I've just pushed an example here: https://github.com/buildkite/rspec-junit-example on how to use our new Build Annotation gear along with a file that parses JUnit errors. If need some help getting it setup or have any questions, feel free to shoot me an email at hello@buildkite.com!

**Comment by KJTsanaktsidis** [comment]
Neato - we're already generating the HTML report output as an artifact so this should be pretty simple for us to drop in.

**Comment by vickeyhuang** [comment]
As our test result, I have generated a html test report on buildkite agent, would you tell me how to integrate this html report on buildkite and also showing well to alert our team?

**Comment by ticky** [comment]
@vickeyhuang if you’re running the beta version of the agent, you can pipe html into the buildkite agent’s annotate command. An example of doing so (with markdown, but it’s roughly the same for html) is here: https://github.com/buildkite/rspec-junit-example/blob/2852116fb75b1d32a68195c9debff4149581c68d/.buildkite/junit.sh#L13-L14

Note that this is a beta feature we’ve not fully finalised or documented yet, so only jump in if you’re comfortable with that!

**Comment by vickeyhuang** [comment]
@ticky thanks your remind, and try to used beta agent annotate, found the annotation limit to 50kb, which is very less.  As our test report, is more than 500kb

+ buildkite-agent annotate
--
  | + cat report/cucumber_report.html
  | 2017-11-24 07:44:47 INFO   Reading annotation body from STDIN
  | 2017-11-24 07:44:51 FATAL  Failed to annotate build: POST https://agent.buildkite.com/v3/jobs/a4d86a9d-3732-4615-9809-23dc2cf091bb/annotations: 400 The annotation body must be less than 50 kilobytes

**Comment by sj26** [comment]
We generally recommend using annotate to call out details you really need somebody to see and take action on. You might like to add an annotation with a [link to your artifact](https://buildkite.com/docs/builds/images-in-log-output#inlining-build-artifact-images) for full test results, and include a summary of the results ("All 200 tests passed" or "3 of 200 tests failed" sort of thing). It's also nice to output failure details, if any, as those are usually what need action. This is how the rspec junit example works, for instance. You could probably [ask cucumber to output junit results](https://relishapp.com/cucumber/cucumber/docs/formatters/junit-output-formatter) and use the same or a similar script as [in the rspec example](https://github.com/buildkite/rspec-junit-example/blob/master/.buildkite/lib/junit.rb) to filter and print failed examples and output a summary.
