### ISSUE TITLE
[Feature Request]: Prioritise builds

### ISSUE THREAD

**Issue by therealbnut** [buildkite/feedback#109]
It would be nice to prioritise builds based on some kind of filter so that code that is reviewed and ready for master isn't blocked by feature branches. Semi-related to #51.

For example, with branch keyword `master` and the commit keyword `[closes #*]`:
- The branch `master` gets a priority of `+1`
- The commit `Some feature [closes #123]` gets a priority of `+1`
- The commit `Some feature [closes #123]` on branch `master` gets a priority of `+2`

**Comment by keithpitt** [comment]
Hey @therealbnut, this is a real interesting idea! :zap: We've got a `[skip ci]` commit filter, but we haven't thought of doing anything special with `[closes]`. The tricky thing with priorities is deployments. Let's say the last step in your build pipeline is a deployment, we may end up deploying commit 3, before commit 1 and 2.

We've thought about doing some prioritisation gear around branches (so `master` builds will run before all others) - would that be close enough do you think?

**Comment by therealbnut** [comment]
Just master would be good (although may not ever be needed #110). Unfortunately it will mean that reviewed and ready branches don't get any prioritisation.

---

A work around for the deployment issue is that the user could ensure all commits in deploy branches have equal priority. So it could be something like: `!master,!deploy:[closes]`.

I was also thinking you could do it with queues, if you can order queues so the `deploy` queue always goes first. After this you could filter what goes to a queue based on commit/branch to send projects to the `deploy`, `feature` or `master` queue.

Nb. I haven't used the queue feature yet, it does appear to be for builds not projects, and probably for filtering clients, not ordering builds.

**Comment by therealbnut** [comment]
Github's PR process has changed now, such that we tend to close pull requests through the web UI, and do not explicitly push a `[closes XYZ]` commit. We're likely going to solve this problem a different way (by having a smaller test-suite for merge commits perhaps), so I'm going to close this issue, thanks :)

**Comment by therealbnut** [comment]
Github's PR process has changed now, such that we tend to close pull requests through the web UI, and do not explicitly push a `[closes XYZ]` commit. We're likely going to solve this problem a different way (by having a smaller test-suite for merge commits perhaps), so I'm going to close this issue, thanks :)
