### ISSUE TITLE
Commits with the same hash on different branches are redundantly re-built

### ISSUE THREAD

**Issue by therealbnut** [buildkite/feedback#110]
In our repo we get this all the time, it means the exact same code gets built twice, often immediately after the previous time.

Steps to reproduce:

```
git checkout master
git merge --ff-only my-green-feature
git push
```

At this point (if `my-green-feature` was able to fast-forward onto master) `master` and `my-green-feature` have the exact same hash.

**Comment by keithpitt** [comment]
Oh weird - which source code provider are you using?

**Comment by therealbnut** [comment]
Github, merging from the PR usually introduces a merge commit so you may not notice this happening. The behaviour should be standard for git though, I would have thought. The commands are essentially pointing master to your feature branch, if it's safe to do so.

**Comment by therealbnut** [comment]
Github has improved its PR workflow now, such that we use merge commits, and enforce a squash merge onto a fast-forward-only master. While this is still an improvement to Buildkite we are unlikely to gain any benefit from it, so I'm closing my issue :)
