### ISSUE TITLE
Update to the new BitBucket webhooks

### ISSUE THREAD

**Issue by toolmantim** [buildkite/feedback#112]
When you set up BitBucket you get a deprecation warning about using old webhooks, which will be deprecated in around 5 months:
http://blog.bitbucket.org/2015/06/24/the-new-bitbucket-webhooks/

**Comment by keithpitt** [comment]
We've pushed support for the new web hooks! If you go to your project settings and find the "Bitbucket Webhook" section, you'll get the details on how to add them :8ball:
