### ISSUE TITLE
Password "is too long"?

### ISSUE THREAD

**Issue by boltronics** [buildkite/feedback#113]
My password manager generates passwords with a random length (between a certain range), which this time happened to be longer than 72 characters. Why is there a 72 character limit?

**Comment by keithpitt** [comment]
@boltronics hey! Good question! We use bcrypt to encrypt and store your password, which itself has a 72 character limit. Here's some reading on why that is: http://security.stackexchange.com/questions/21524/bcrypts-72-character-limit-and-using-it-as-a-general-digest-algorithm and https://en.wikipedia.org/wiki/Bcrypt

**Comment by boltronics** [comment]
That's unfortunate. scrypt and PBKDF2 don't have such a limitation...
