### ISSUE TITLE
Feature Request: Implement user access controls

### ISSUE THREAD

**Issue by vacri** [buildkite/feedback#115]
At the moment there is no user limitation beyond 'do not allow to create new users'. User access controls would be a useful addition

I'd suggest this as a minimum starting point:
- global default per user of 'nothing/readonly/write'
- per buildplan 'block/readonly/write' per user

This would allow you to make a readonly user that has write access to buildplan X and Y, or a globally blocked user than can only access one plan (eg, for a temp contractor)

My own usecase has an admin user (me and my special mates) and a dev user. I don't mind the dev users messing around with their own plans, but I'd like them to be readonly for production plans.

Any design should allow for future implementation of user groups. BitBucket user management is like this, with users and groups both having a global default with per-repo alterations available.

**Comment by keithpitt** [comment]
We now have user access controls behind a feature flag. It's a new "Teams" feature we've been working on. If you're interested in learning more, feel free to email hello@buildkite.com
