### ISSUE TITLE
Fliters in Agents API

### ISSUE THREAD

**Issue by EmilS** [buildkite/feedback#118]
Similar to how the builds API has the ability to filter by state, branch, etc., it'd useful to be able to add filters when querying the Agents API. One of those filters should be `hostname`.

**Comment by toolmantim** [comment]
![](https://media1.giphy.com/media/jxTnOS8Mkv8n6/200_s.gif)

That's now live: https://buildkite.com/docs/api/agents#list-agents (see below the example for the list of query string parameters, you can now filter on hostname, name and version)

**Comment by EmilS** [comment]
![](http://gifs.stolarsky.com/clap/applause.gif)
