### ISSUE TITLE
Artifact content type no longer retained, can't easily view artifacts in browser

### ISSUE THREAD

**Issue by nickbrowne** [buildkite/feedback#119]
I'm not sure if this is our own fault for misconfiguring something, but we used to be able to view things like simplecov reports in the browser, via the links in the artifacts tab.

It seemed to work up until quite recently, here's a build from about 2 weeks ago where the artifacts load in the browser, instead of downloading:
https://buildkite.com/conversation/tc/builds/14198#6a028a43-d309-452b-b5c6-2a3ead960739

But in newer builds attempting to view coverage causes the browser to download the artifact:
https://buildkite.com/conversation/tc/builds/14507#122e7950-6a27-40bd-a2af-52e37d6c457c

curling the artifact urls reveals that previously, the Content-Type seemed to be retained. With older builds, HTML artifacts have a content type of `text/html`, pngs were `image/png` and so on. In more recent builds, the content type of everything seems to be `binary/octet-stream`.

I'm a bit unsure how to debug this further, I wonder if you guys have changed anything recently that may cause this behaviour? 

Is there a way to configure the artifact uploader so that it retains the content type?

Thanks!

**Comment by keithpitt** [comment]
@nickbrowne hey! Yeah, you're right, we did change something. And it looks like it's had a negative effect in this regard.

So previously we used to upload artifacts to our own S3 bucket, mark them as "public-read" and obfuscate the URL. That meant if anyone got ahold of the URL, they'd get access to the artifact. This wasn't ideal, so we changed it so all artifacts are set to "private-read" - which requires a special token to access.

Now when you go to download a URL, you're given a special URL that is only valid for a few minutes - after that you can't access the resource anymore (unless you request a new URL). It sounds like using this approach has broken your workflow, that sucks, sorry about that :(

I can look into other ways of handling this. I think a work around solution for now would be for you to use your own S3 bucket for artifacts (which is easy to setup) https://buildkite.com/docs/agent/build-artifacts#using-your-own-s3-bucket that way you can set the files to `public-read` and you'll get the same behaviour as before.

**Comment by nickbrowne** [comment]
Ah interesting, I can see why that change would be made. I'll look into having our own S3 bucket, but as we currently just use cloudfiles, we may just put it with it for now!

Thanks for the quick response :)

**Comment by essen** [comment]
Hello, I got redirected here from Twitter.

I also run into this issue. I have two types of artifacts: text/plain files, and folders full of html and related files. Both are kinds of logs from the different testing tools.

Text/plain files I don't want to be forced to download, I just want to see them, maybe fix something or rollback and try again.

HTML logs it's a bit similar, I want to see them in my browser. But there's another issue: as far as I understand, I can't easily tell BuildKite to upload the whole folder. I could tar it, but then I have to download that, extract it and so on just to see some extra information.

I do not have any S3 or anything like that. I do not mind the files being public personally, it's public projects.

As far as artifacts go, my best experience was on CircleCI, where it picks up the whole folder. The HTML logs was a slow upload initially though (the folder can be hundreds of small files) but they fixed that. They still have a pretty slow display of the directory listing etc. though.

Note that for the purpose of UI, I only need links to two of those HTML files, not a directory listing or anything like that.

**Comment by keithpitt** [comment]
It's something I'd love to fix, hopefully we can get to it soon! Sorry that it's causing you some frustration :(

**Comment by toolmantim** [comment]
Hi there! Just updating this old ticket. We've actually fixed most of the content types since this was updated. If there's any that we're specifically not handling correctly, please open an issue or email support and we'll get it fixed.

**Comment by airhorns** [comment]
Hey @toolmantim do you know if you folks set the content type on artifacts uploaded to s3 when we're using our own buckets? If so, are gzipped files included in the list of types you manage? I am uploading `something.csv.gz` files and getting them back as `binary/octet-stream` from our own s3 bucket.

**Comment by toolmantim** [comment]
Ah, sorry @airhorns — having checked, I think it's broken for private buckets still. I believe buildkite/agent#494 is working to address this — let's take this discussion to the agent repository.

**Comment by airhorns** [comment]
@toolmantim I actually opened that PR and I got confused when writing the title, it's actually about content-encoding, and the content-type stuff works fine, so all good on this issue :)
