### ISSUE TITLE
Builds triggered via GitHub Webhooks have no creator

### ISSUE THREAD

**Issue by byroot** [buildkite/feedback#122]
It would be nice if the creator was the pusher in the github hook: https://developer.github.com/v3/activity/events/types/#pushevent

```json
{
 ...
  "pusher": {
    "name": "baxterthehacker",
    "email": "baxterthehacker@users.noreply.github.com"
  },
...
}
```

**Comment by byroot** [comment]
cc @mcgain

**Comment by byroot** [comment]
Actually thinking about it, the reason might be that most people GitHub email doesn't match their buildkite account email.

**Comment by keithpitt** [comment]
@byroot yup! The creator should be their user record. Easiest way is for them to connect their GitHub account to Buildkite (or manually add their git email). We'll working on rolling out some screens that'd make it more apparent for users that they should do this.

**Comment by JamelZarin** [comment]
Please advice me to do so because i still in learning #
