### ISSUE TITLE
Bug: incorrect branch name in build directory

### ISSUE THREAD

**Issue by vacri** [buildkite/feedback#124]
The environment setup has a problem for non-master branches, where the branch is not correctly named in the build. There is a step in the setup process where `git reset --hard origin/branchname` is called, but this does not switch to the new branch. Instead, it overwrites the current branch (master) with the origin branch's files - you end up with a branch named 'master' with the desired branch's files and commits. As the 'wrong' commits are now in local master, the `git checkout [hash]` command doesn't switch the branch name (though it does get you the right files).

This can cause problems if the buildplan scripts have actions that differ on branch names. 

Here is the `reset --hard` switching the files without switching the branch:

``` bash
# 'master' and 'dist' have completely different filesets
paul@melchett:~/tmp/branch-tester$ git branch
* master
paul@melchett:~/tmp/branch-tester$ ls
bower.json  build  favicon.ico  gulp.config.js  gulpfile.js  gulp.png  karma.conf.js  package.json  README.md  README.text  src
paul@melchett:~/tmp/branch-tester$ git reset --hard origin/dist
HEAD is now at a7f75ab trivial commit to test something in Buildkite
paul@melchett:~/tmp/branch-tester$ git branch
* master
paul@melchett:~/tmp/branch-tester$ ls
bootstrapper  ecal-index.html  favicon.ico  fonts  images  index.html  js  langs  styles
```

It also doesn't matter if you have the non-master branch locally:

``` bash
# 'master' and 'dist' have completely different filesets
paul@melchett:~/tmp/branch-tester$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
paul@melchett:~/tmp/branch-tester$ ls
bower.json  build  favicon.ico  gulp.config.js  gulpfile.js  gulp.png  karma.conf.js  package.json  README.md  README.text  src
paul@melchett:~/tmp/branch-tester$ git branch
  dist
* master
paul@melchett:~/tmp/branch-tester$ git reset --hard origin/dist
HEAD is now at a7f75ab trivial commit to test something in Buildkite
paul@melchett:~/tmp/branch-tester$ ls
bootstrapper  ecal-index.html  favicon.ico  fonts  images  index.html  js  langs  styles
paul@melchett:~/tmp/branch-tester$ git branch
  dist
* master
paul@melchett:~/tmp/branch-tester$ git diff master dist
paul@melchett:~/tmp/branch-tester$ 
```

I imagine the fix is to add `git checkout [branch]` to switch to the correct location before the `reset --hard`

**Comment by porty** [comment]
I'm of the opinion that if you're not actively doing development in a repo (like a repo you depend on or a CI box) then you don't need any local branches at all - you could run `git checkout origin/branchname` and work off a "detached head" checked out at the remote location (requires a `git fetch` beforehand to get the local reference in the first place):

```
$ git checkout origin/master
Note: checking out 'origin/master'.
...
HEAD is now at a157321... Merge pull request #1051 from 99designs/cleanup-features-etc
$ git branch
* (HEAD detached at origin/master)
```

Not sure how this works out for Buildkite in their display of the branch that it is on, but that's my 2c

**Comment by vacri** [comment]
I think it should match the branch/tag you specify, which keeps it true to POLA.

My use case is that I have a final script that does deployment (after a manual unlock) and also sends notifications out to a couple of places saying "branch foo build bar deployed to baz". Currently that says 'master' regardless of build branch, as it takes it from the current git dir. The script is also used outside buildkite, so setting the notifications via the buildkite env vars isn't really an option.

**Comment by keithpitt** [comment]
It'd be nice if we could make it "just work" - so yours and anyone else's scripts that check the branch will continue to work when they switch to Buildkite. We need to figure out which commands will work (those sequence of commands have gone through a few iterations because of problems with the right commit not being checked out - but I can't really remember). I'll need to check through the git history to see what we used to have.

In the mean time, you can always use `$BUILDKITE_BRANCH`

**Comment by vacri** [comment]
With the caveat that I'm not a world-class gitter, for a 'clean build' I think all you would need to do is put `git checkout [branch/tag]` in the step before the `git reset --hard [branch/tag]`. The checkout would set the label to the requested tag, and the subsequently reset replaces all files with those from the same label (clearing out cruft).

I'm not familiar with the steps for a non-clean build, so I'm not aware of what should happen there. I wouldn't have thought a `git checkout [tag]` before any code wrangling could cause a problem, though.

**Comment by toolmantim** [comment]
@vacri at the moment we do a git checkout of the commit https://github.com/buildkite/agent/blob/master/templates/bootstrap.sh#L237 so it should never show an "incorrect" branch name (like in your example above)

This is running the commands manually:

```
$ BUILDKITE_COMMIT=70365fa93d19312a4754d8fe3769c1fcd5c5b356
$ BUILDKITE_BRANCH=comment-out-defaults-on-linux
$ cd /tmp
$ mkdir agent
$ cd agent/
$ git clone https://github.com/buildkite/agent.git . -qv
Cloning into '.'...
POST git-upload-pack (gzip 3740 to 1877 bytes)
remote: Counting objects: 5906, done.
remote: Total 5906 (delta 0), reused 0 (delta 0), pack-reused 5906
Receiving objects: 100% (5906/5906), 3.44 MiB | 701.00 KiB/s, done.
Resolving deltas: 100% (3717/3717), done.
Checking connectivity... done.
$ git clean -fdq
$ git fetch -q origin $BUILDKITE_COMMIT 2> /dev/null || git fetch -q
$ git reset --hard origin/$BUILDKITE_BRANCH
HEAD is now at 70365fa Don't set defaults in the cfg that don't need to be set
$ git checkout -qf "$BUILDKITE_COMMIT"
$ git branch
* (HEAD detached at 70365fa)
  master
```

I'm guessing you're using the following command to find out what `HEAD` is pointing to?

```
$ git rev-parse --abbrev-ref HEAD
HEAD
```

To make that command return what you'd get in a dev environment, we'd need to some more funky town, because:

```
$ git checkout -f -b "$BUILDKITE_BRANCH" "$BUILDKITE_COMMIT"
Switched to a new branch 'comment-out-defaults-on-linux'
$ git checkout -f -b "$BUILDKITE_BRANCH" "$BUILDKITE_COMMIT"
fatal: A branch named 'comment-out-defaults-on-linux' already exists.
```

**Comment by keithpitt** [comment]
I've done some googling and have played around with a few ideas locally, but I haven't figured out a way get the repo into the state we want it, and also preserve `./git/HEAD`. No matter what I do, I always end up in a detached head.

**Comment by vacri** [comment]
@toolmantim you are correct in that I'm using the rev-parse trick to get the current branch. For my use case, I'll fiddle with the script and look for env vars. I'm past the limit of my git understanding, so can't suggest something intelligent from here.

I guess that if this issue hasn't really been a problem by this stage, it's small enough that it's not hitting a lot of use-cases. Happy to have the ticket closed/backlogged.

**Comment by toolmantim** [comment]
What about changing:

```bash
buildkite-run "git checkout -qf \"$BUILDKITE_COMMIT\""
```

to:

```bash
buildkite-run "git checkout -qf -B \"$BUILDKITE_BRANCH\" \"$BUILDKITE_COMMIT\""
```

**Comment by TimMoore** [comment]
This workaround in our deployment script seems to put us in the right state:

```bash
git checkout $BUILDKITE_BRANCH
git reset --hard $BUILDKITE_COMMIT
```

**Comment by toolmantim** [comment]
Thanks for all the feedback and reports. We've changed this code quite a bit since then. I'm going to close this issue for now, but if it's still affecting you please re-open it.
