### ISSUE TITLE
Code folding: strip ANSI before figuring out if a line is a fold

### ISSUE THREAD

**Issue by alexjurkiewicz** [buildkite/feedback#128]
Sometimes I am using `sed` on coloured test output to create buildkite folds, but if I don't set 'no colour' ANSI escape sequence before the fold mark, buildkite won't create a fold.

![screen shot 2015-10-14 at 2 03 25 pm](https://cloud.githubusercontent.com/assets/379509/10474314/04da7a3a-7281-11e5-8359-b402bd6fba13.png)

It would be nice if buildkite handled this case

**Comment by keithpitt** [comment]
@alexjurkiewicz oh! We should have closed this ages ago - a while ago we shipped a fix that stripped colours from those headers so we should spot them correctly. Sorry for not letting you know sooner!
