### ISSUE TITLE
Feature Request: Custom 'commit status' names.

### ISSUE THREAD

**Issue by SomeoneWeird** [buildkite/feedback#131]
Currently commit status names are `buildkite/{project}`, i'd like to be able to customize that per-project or at least have the same name across every project (`buildkite` etc)

**Comment by keithpitt** [comment]
Interesting idea! What's the use case of having it just be `buildkite`?

**Comment by SomeoneWeird** [comment]
Basically I'm adding status check.. checks to [githubwrangler](https://github.com/SomeoneWeird/githubwrangler) so we can ensure that all CI checks pass before people can merge PRs. I think having something like:
```
{
  type: "status",
  checks: [ "buildkite" ]
}
```
would be a little nicer than
```
{ 
  type: "status",
  checks: [ "buildkite/{{repo}}" ]
}
```
I managed to get around this by allowing you to interpolate the repo name in the check, I was tired when I made this issue and obviously didn't think that was technilogically possible to do - so this is less of an issue now :) :heart: buildkite

**Comment by keithpitt** [comment]
Ok cool - awesome! I'm glad you got it all working :D:D I'll close this issue for now then.

`githubwrangler` looks like an interesting project though!

**Comment by ljharb** [comment]
@keithpitt I'd love to be able to customize the names of individual statuses for build steps (https://twitter.com/ljharb/status/973470308907667457) - any chance of that happening? (posting it here because it seems related)
