### ISSUE TITLE
[Feature request] Allow pruning of old branches

### ISSUE THREAD

**Issue by stajs** [buildkite/feedback#132]
When viewing a project on the website, it is annoying to see lots of panels for old branches that don't exist anymore. Please allow the ability to remove them from the list. Even better, auto-prune based on the available branches from GitHub.

**Comment by stajs** [comment]
It looks like you guys are way ahead of me, noticed this today:

![image](https://cloud.githubusercontent.com/assets/2253814/11484183/87037010-9811-11e5-8092-9e0267e0a1ea.png)

**Comment by keithpitt** [comment]
Ha! Yeah! Sorry, we should have closed this issue when we rolled this feature out! Thanks for suggesting it! I think your suggestion was finally the one where we were like: "We should just go do this :D" :+1:

**Comment by stajs** [comment]
That's cool. Let me tell you, as a user of your product, touches like this where you feel like your feedback has an effect on things is pure gold from the touchy-feely-vibes dept.

Keep rocking. :dancers:

**Comment by keithpitt** [comment]
Nawww, thanks! :heart:
