### ISSUE TITLE
Bug: deploy sha fails

### ISSUE THREAD

**Issue by mkllnk** [buildkite/feedback#134]
I tried to use the Github deploy API and created a deploy with a sha commit id as `ref`. Buildkite fails to prepare the repository:

```
	Preparing build folder
$ mkdir -p "/var/buildkite-agent/builds/CI/open-food-foundation/open-food-network-staging1"
$ cd "/var/buildkite-agent/builds/CI/open-food-foundation/open-food-network-staging1"
$ git clean -fdq
$ git submodule foreach --recursive git clean -fdq
$ git fetch -q
$ git reset --hard origin/863d448ffc0a4e4c5b2da872560b7759335ab6e4
fatal: ambiguous argument 'origin/863d448ffc0a4e4c5b2da872560b7759335ab6e4': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

https://buildkite.com/open-food-foundation/open-food-network-staging1/builds/182#8e982de1-975f-498f-9336-365876ffb4f1

I can set `ref` to a branch or tag name, but some people may want to build a commit without name.

**Comment by keithpitt** [comment]
Ahhh, I think I see what's happening now. Since we don't know the branch (only the commit) we make the branch the commit as well, and when we try and reset to that branch, it breaks. So yeah, you've found a bug :D Could you copy the issue over here for me? :D:D http://github.com/buildkite/agent

**Comment by keithpitt** [comment]
Thanks for letting us know! <3

**Comment by mkllnk** [comment]
Copied to buildkite/agent#220. Thank you. :-)
