### ISSUE TITLE
Overriding Environment Variables in Manual Build

### ISSUE THREAD

**Issue by superarts** [buildkite/feedback#138]
If the environment variable is set in project setting, it cannot be overriden by the one I pass in manual build. It seems to be a bit weird in design aspect.

**Comment by keithpitt** [comment]
Hey @superarts - sorry for such an incredibly late response to this issue! I've just pushed out a fix so this is the behaviour now. Environment variables you enter in the "Trigger Build" UI will now override those provided by the steps as defaults!

**Comment by superarts** [comment]
Thanks!
