### ISSUE TITLE
HTML Hyperlink Markup for output

### ISSUE THREAD

**Issue by meylor** [buildkite/feedback#139]
It would be cool if a properly formatted line would appear as a hyperlink in the console output from a build, such as 

```
<buildkitehyperlink>https://buildkite.com/myorg/mybuild/builds/mynum</buildkitehyperlink>
``` 

or 

```
<buildkitehyperlink>https://mycompany.com/dashboard</buildkitehyperlink>
```

**Comment by toolmantim** [comment]
I like the idea. Have you got a good example of some output where you're wanting to use it?

**Comment by meylor** [comment]
Below is the sanitized output from a job that I have; I'd love to be able to click the links (if they're wrapped in a tag).

```
Preparing build folder	2.4s
Running global pre-command hook	0.5s
Running command	9m 56.6s
$ cd ci
python wrapper.py
Dependency app1: https://buildkite.com/myorg/packer-build/builds/485
Dependency app2: https://buildkite.com/myorg/packer-build/builds/486
Dependency app3: https://buildkite.com/myorg/packer-build/builds/487
Running dependency builds |..............................  | 95%
[?25h
service=app1                exit_status=True
service=app2                exit_status=False
service=app3                exit_status=True
one of the dependencies failed. exiting.
```

**Comment by meylor** [comment]
@toolmantim I was working through Buildkite today, and remembered this issue. Just +1'ing it again, because it would be a great feature

**Comment by keithpitt** [comment]
@meylor you can actually kinda do this now!

https://github.com/buildkite/terminal#links and...
https://github.com/buildkite/terminal/blob/master/link.sh

We use escape codes to determine if something should be a link or not. So you can do something like this: `\033]1339;url=https://google.com;content=Google Search` and it'll show a link in the build output. You can even use a similar syntax to embed images :)

Let me know how you go!!
