### ISSUE TITLE
Schedule recurring nightly builds

### ISSUE THREAD

**Issue by jamesottaway** [buildkite/feedback#145]
I'd love to be able to schedule nightly builds, which can alert me to any intermittent issues while a project is sitting idle.

I've often found that resuming work on an old project means that the first time I trigger a new build it will fail for a reason unrelated to the new change I've just made.

Triggering daily builds, regardless of activity on the project means I can easily identify when transient build failures begin.

**Comment by keithpitt** [comment]
Ah yeah, this has been on our TODO list for some time. We've got a new person starting in a few weeks, so hopefully that gives us a bit more capacity to get this feature out :) We'll let you know when it's ready!

**Comment by deanperry** [comment]
This sounds like a pretty neat idea!

**Comment by toolmantim** [comment]
This is a duplicate of #61 — go follow that one for updates!
