### ISSUE TITLE
Feature request: If you click on “Running” or “Scheduled” and there’s only 1 in that category, go straight to the build

### ISSUE THREAD

**Issue by SomeoneWeird** [buildkite/feedback#148]

**Comment by keithpitt** [comment]
(from 2 years ago!) I might close this one @SomeoneWeird.

Thinking about it, I think you'd probably be quite confused if a link in the UI changed destination depending on how many items it wants to show...

For example, you may have 2 running builds - click the link, and by the time the request gets to the server - the other build has finished. If we did the "take you to the build if there's only one" you'd be like "whaaa, I was expecting to see 2 builds, but now I'm on a build page - how did I get here"

Hopefully that sounds fair!

**Comment by SomeoneWeird** [comment]
Yeah fair enough 👍
