### ISSUE TITLE
'Retry' button should be shown on timed out jobs

### ISSUE THREAD

**Issue by danny-wu** [buildkite/feedback#149]
#86 implemented the much appreciated functionality to retry failed jobs individually, however it'd be nice if timed out jobs also have retry.

<img width="934" alt="screen shot 2016-02-10 at 1 31 18 pm" src="https://cloud.githubusercontent.com/assets/16657108/12937272/28afcf96-cffb-11e5-92c6-99029ec1d7ec.png">

**Comment by keithpitt** [comment]
Hey @danny-wu - this is a top idea! I've just pushed this now, so you should be able to retry timed out jobs :) :dancers:

**Comment by marcfallows** [comment]
Hey @keithpitt, did this regress in a recent update? The retry button on timed out jobs seems to be missing again.

**Comment by keithpitt** [comment]
@marcfallows yeah, my fault! Shipping a fix now!

**Comment by keithpitt** [comment]
@marcfallows fixed! You should be able to retry timed out jobs now. Sorry about that!

**Comment by marcfallows** [comment]
Amazing. Thanks for the quick fix @keithpitt! Just retried a timed out job 👌

**Comment by keithpitt** [comment]
Perfect :)
