### ISSUE TITLE
Show steps in Hipchat

### ISSUE THREAD

**Issue by leevigraham** [buildkite/feedback#150]
Hey guys,

I've hooked buildkite Notifications up to Slack & Hipchat to test. Slack shows the stages of my build while Hipchat does not. Not sure if it's possible but it would be great to see when a pipeline was unlocked in HipChat.

<img width="951" alt="screen shot 2016-02-25 at 11 53 46 pm" src="https://cloud.githubusercontent.com/assets/25124/13320179/0e5c813a-dc1b-11e5-81cc-3e63dd946ce3.png">

<img width="795" alt="screen shot 2016-02-25 at 11 49 58 pm" src="https://cloud.githubusercontent.com/assets/25124/13320138/a53e639e-dc1a-11e5-833a-404aa005b99d.png">

<img width="785" alt="screen shot 2016-02-25 at 11 49 33 pm" src="https://cloud.githubusercontent.com/assets/25124/13320139/a54326cc-dc1a-11e5-8b1f-c7d03ef2ff8f.png">

**Comment by toolmantim** [comment]
Hey, we've just sent this live for you! You should now get a notification when someone unblocks the step. Let me know how it goes for you :)

**Comment by leevigraham** [comment]
Thanks @toolmantim !
