### ISSUE TITLE
Environment variable validation/sanitisation

### ISSUE THREAD

**Issue by hatt** [buildkite/feedback#151]
On the project settings page, env vars are set in a free-text field. It would be great if each key=val pair could be pseudo-validated to make sure no invalid characters are present, such as a space. Right now it's difficult to debug when someone has pasted/written a value incorrectly, and some basic sanitisation would save on frustration.

**Comment by keithpitt** [comment]
@hatt (sorry for such a late reply!) we validate environment variables now when using YAML based UI steps (you can find our more about them here: 
https://forum.buildkite.community/c/beta-support-feedback/yaml-pipeline-steps)

Thanks for the suggestion - and sorry it took so long for us to get around to it!
