### ISSUE TITLE
Build page job list doesn't show wait steps

### ISSUE THREAD

**Issue by sj26** [buildkite/feedback#154]
It might be nice if the list of jobs on the build page showed some visual indication of wait steps as you scroll down the page. The little chevrons make it easy to see what steps have waits in the summary at the top, but it is a little more confusing as you scroll down and view various jobs and their outputs. A discrete divider or rule, maybe?

**Comment by keithpitt** [comment]
I believe we added this! And I think even you added it @sj26 :)

**Comment by sj26** [comment]
I did! 😅
