### ISSUE TITLE
Environment variables text entry as a monospace font

### ISSUE THREAD

**Issue by Bockit** [buildkite/feedback#155]
Is it possible to make the environment variables textareas in build settings a monospaced font? Just ran into an issue with a leading space and my natural reaction is to blame my tools ;)

Thanks for your time and a great product!

**Comment by toolmantim** [comment]
Thanks for the feedback! This is something we'll change for sure, I'll keep you posted.

**Comment by toolmantim** [comment]
We’ve updated the textareas of both the job command, job environment variable, project environment variable and then the command on the job itself. (it also now autoresizes as well!) Thanks for the feedback :)

**Comment by Bockit** [comment]
Nice one, thanks!
