### ISSUE TITLE
Show the master branch on the pipelines page

### ISSUE THREAD

**Issue by KJTsanaktsidis** [buildkite/feedback#156]
I'm evaluating Buildkite for our organisation at the moment, and one of the things I found irritating is that the "pipelines" page shows the status for the latest build for each pipeline, rather than the latest build on the master branch.

E.g.:

![image](https://cloud.githubusercontent.com/assets/1418177/14772798/8c20176e-0ae5-11e6-941d-8d34852be279.png)

What I really want from this page is the ability to glance over each of our projects and see if the master build is currently passing or failing. It's not particular interesting whether or not the latest feature branch to be built has passed - they're of course going to fail as developers work on the feature!

Is there a knob I can twiddle somewhere?

**Comment by keithpitt** [comment]
@KJTsanaktsidis no knob at the moment I'm afraid, but I hear you about that page!

We've started actually rebuilding this page a few days ago, and that whole bottom section is getting the boot. We're replacing it with exactly what you suggested actually :) So stay tuned!

**Comment by keithpitt** [comment]
@KJTsanaktsidis took a while to get it over the line, but we finally did this exact thing! https://building.buildkite.com/new-in-buildkite-pipeline-metrics-b5e7bf187272

<img width="967" alt="screen shot 2016-11-03 at 5 45 55 pm" src="https://cloud.githubusercontent.com/assets/25882/19961396/64f551a0-a1ed-11e6-80de-8f782ab554d4.png">
