### ISSUE TITLE
Retain console log when retrying failed step

### ISSUE THREAD

**Issue by jamesottaway** [buildkite/feedback#157]
I nearly always end up hitting the 'Retry' button when a step fails for an intermittent reason on a critical build (ie. anything on `master`), but losing the history of the failure makes it difficult to reference a failed step for later debugging.

I take it this was a trade-off made to ship the 'Retry' feature in the first place, but I figure it's not out of the realm of possibility to add an "attempt" concept to the way steps are modelled.

Thoughts?

**Comment by keithpitt** [comment]
@jamesottaway yeah, it's a little bit sucky... And you're right, when we first built Retry, the easiest way for us to get it over the line was to just scrap the existing logs and artifacts and return the job to a `scheduled` state. There's no reason why we can't show the previous attempts though!

It's definitely on our list of things to improve though!

**Comment by jamesottaway** [comment]
Didn't the "retain previous step logs" feature launch recently?

**Comment by toolmantim** [comment]
It did @jamesottaway! https://building.buildkite.com/new-in-buildkite-job-retries-3f60a8d45ed2

Sorry for not updating this earlier @petemounce
