### ISSUE TITLE
Trigger pipeline when GitHub Pull Request is updated/synchronized

### ISSUE THREAD

**Issue by vaughandroid** [buildkite/feedback#158]
We run pipelines on Pull Requests, to ensure tests all pass before merging. We would like the job to re-run when the PR gets updated - i.e. when new commits are pushed to the branch to be merged in. This is fairly common as a result of code reviews or failing tests.

Our current workaround for this is to set GitHub to also send "Push" events, and have the pipeline steps run conditionally based on the `BUILDKITE_PULL_REQUEST` environment variable. It's a bit cumbersome though.

GitHub sends a PR event with `"action": "synchronize"`, so it should be fairly straightforward to just respond to those. I guess you might want to make this behaviour optional to avoid breaking things for users who are already using similar workarounds?

**Comment by keithpitt** [comment]
Hey @vaughandroid - thanks for the feedback! I'm a bit confused by the request I'm afraid! Or I could be totally missing something :P

We already trigger pipeline builds when you push commits to a Pull Request (which we do via the `push` event like you described, which is one of the required webhook events we need).

**Comment by toolmantim** [comment]
(sorry, I was given extra context in Slack and didn't put it here)

I believe @vaughandroid wants to run PR-only builds on this specific pipeline, but there's no branch filter pattern that will work for it. He was looking for a "Only build pull requests" type option, and one workaround was to try to disable the `push` GitHub webhook event.

I believe he ended up adding back `push`, and checking the presence of `BUILDKITE_PULL_REQUEST` env and aborting the build if it wasn't present. But it'd be nicer if there weren't a bunch of failed builds.

Feel free to correct me if I'm mistaken @vaughandroid

**Comment by keithpitt** [comment]
Ah right, I see now :)

So what you do is have a "Branch filter pattern" of `lol-this-will-never-exist` inside the "Branch Limiting" section for the pipeline you want to limit to be "pull request only".

Pull request builds will override any Branch Limiting settings, so by using `lol-this-will-never-exist` as a branch filter, only commits on that branch and pull requests will trigger builds, and since that branch will never exist, only pull request builds will trigger.

<img width="753" alt="screen shot 2016-05-06 at 1 50 53 pm" src="https://cloud.githubusercontent.com/assets/25882/15064266/929f2166-1391-11e6-9baf-7c0ca74da639.png">

**Comment by vaughandroid** [comment]
Thanks for the help guys. I noticed yesterday our attempted workaround wasn't working so I'll try your suggestion @keithpitt 

It would still be nice if the Pull Request "synchronize" events could be made to trigger builds, but assuming this workaround works then it's not urgent for us.

**Comment by sschaetz** [comment]
This is cool. Is there a way to add branch filter to `pipeline.yaml` (pipeline upload)?

**Comment by keithpitt** [comment]
Hey @vaughandroid - we pushed out a few weeks ago the ability to only specify which branches you'd like to build pull requests for :) I'm sorry I totally forgot to come back to the issue and update it!

![screen shot 2016-10-31 at 11 22 43 am](https://cloud.githubusercontent.com/assets/25882/19841233/5d2c23ba-9f5c-11e6-9e0b-21c66dad4bc5.png)

@sschaetz you can filter branches in the `pipeline.yml` file like so:

```
steps:
  - command: "blah.sh"
    branches: "this-branch-only"
```

You can find some more info about what options are allowed here: https://buildkite.com/docs/guides/uploading-pipelines
