### ISSUE TITLE
Gogs / other Git repo support

### ISSUE THREAD

**Issue by deanpcmad** [buildkite/feedback#160]
I'm currently running my own Gogs server on DigitalOcean to host my Git repos. I'm currently using the Buildkite API to create builds with the `post-receive` git hook (using the code below).

I'd like to be able to use webhooks like the other services instead  :)

``` bash
#!/bin/sh

set -u

while read oldrev newrev ref
do
  branch=$(echo $ref | cut -d/ -f3)
  author=$(git log -1 HEAD --format="format:%an")
  email=$(git log -1 HEAD --format="format:%ae")
  message=$(git log -1 HEAD --format="format:%B")

  echo "[Buildkite] - Sending build request..."

  curl "https://api.buildkite.com/v1/organizations/ORG/projects/PROJ/builds?access_token=XXX" \
    -s \
    -X POST \
    -F "commit=${newrev}" \
    -F "branch=${branch}" \
    -F "author[name]=${author}" \
    -F "author[email]=${email}" \
    -F "message=${message}"
  echo ""
done
```

**Comment by sj26** [comment]
The best way to support any custom Git repo is probably like you've done, with a script calling the Buildkite API. :-)

Looks like Gogs also supports their own version of webhooks:

https://gogs.io/docs/features/webhook

Perhaps at some point we can integrate support for these, too, making it a little more seamless. Deep web linking for commits and things is kinda nice, too.

**Comment by deanpcmad** [comment]
Hey, I was wondering if you've managed to look into supporting Gogs as I'd like to just use the webhook system instead of having to copy and paste that shell script every time 😄 

I've created a test repo and created a webhook URL as a requestbin. The details are here:

```
Content-Type: application/json
Cf-Connecting-Ip: 138.68.152.175
X-Gogs-Delivery: cf25287e-ab8d-4bc0-9ef7-833e45b19c9a
Connect-Time: 0
X-Request-Id: bc2d7238-3b8b-4278-9080-bd073b7fccc2
Cf-Ray: 2e60039915a335f6-LHR
Content-Length: 1829
Cf-Ipcountry: US
Total-Route-Time: 0
Connection: close
Cf-Visitor: {"scheme":"http"}
Via: 1.1 vegur
Host: requestb.in
Accept-Encoding: gzip
X-Gogs-Event: push
User-Agent: GogsServer
```

And the request body is:

```json
{
  "secret": "",
  "ref": "refs/heads/master",
  "before": "730110f62d3e8a6c58dcd0df5d064b8b46313364",
  "after": "7a767e076a253ff5a7565a10fe8b92f200e4ba98",
  "compare_url": "https://gogs-url.com/dean/test/compare/730110f62d3e8a6c58dcd0df5d064b8b46313364...7a767e076a253ff5a7565a10fe8b92f200e4ba98",
  "commits": [
    {
      "id": "7a767e076a253ff5a7565a10fe8b92f200e4ba98",
      "message": "Update 'README.md'\n",
      "url": "https://gogs-url.com/dean/test/commit/7a767e076a253ff5a7565a10fe8b92f200e4ba98",
      "author": {
        "name": "dean",
        "email": "dean@voupe.com",
        "username": "dean"
      },
      "committer": {
        "name": "dean",
        "email": "dean@voupe.com",
        "username": "dean"
      },
      "timestamp": "2016-09-21T19:44:49Z"
    }
  ],
  "repository": {
    "id": 8,
    "owner": {
      "id": 1,
      "username": "dean",
      "full_name": "",
      "email": "dean@voupe.com",
      "avatar_url": "https://gogs-url.com/avatars/1"
    },
    "name": "test",
    "full_name": "dean/test",
    "description": "",
    "private": true,
    "fork": false,
    "html_url": "https://gogs-url.com/dean/test",
    "ssh_url": "git@gogs-url.com:dean/test.git",
    "clone_url": "https://gogs-url.com/dean/test.git",
    "website": "",
    "stars_count": 0,
    "forks_count": 0,
    "watchers_count": 1,
    "open_issues_count": 0,
    "default_branch": "master",
    "created_at": "2016-09-21T19:35:20Z",
    "updated_at": "2016-09-21T19:35:53Z"
  },
  "pusher": {
    "id": 1,
    "username": "dean",
    "full_name": "",
    "email": "dean@voupe.com",
    "avatar_url": "https://gogs-url.com/avatars/1"
  },
  "sender": {
    "id": 1,
    "username": "dean",
    "full_name": "",
    "email": "dean@voupe.com",
    "avatar_url": "https://gogs-url.com/avatars/1"
  }
}
```

**Comment by keithpitt** [comment]
👋 We don't have an ETA on when we'll build in Gogs support just yet. Perhaps we may roll back around this in the future, but I'll close this issue for now.

Since the hook-script solution works for the most part, I think that's OK for now :)

**Comment by techknowlogick** [comment]
Alas, the hook-script solution does not work for everyone as unless you are an admin of a gitea/gogs server instance then you can't change them (unless the admin gives you those permissions). There is also the case where you are an admin of an instance, and the server admin disabled the ability for Gogs/Gitea admins from changing it. I would have to connect another CI system to trigger buildkite.

Gitea (a community fork of Gogs) supports Gogs webhooks, as well as offers improved Gitea webhooks. Also Gitea supports commit statuses (so you can see if a commit failed or was successful via the webinterface).

Bias Note: I am one of many maintainers of Gitea, however I am not commenting here in any official capacity, I just want buildkite to accept Gitea (or at the very least Gogs) webhooks so that I can send builds directly to it from the Gitea instance I use unrelated to my open source contribution specifically to Gitea.
