### ISSUE TITLE
Feature Request: Job lookup by id

### ISSUE THREAD

**Issue by casperisfine** [buildkite/feedback#161]
### Context:

Since https://github.com/buildkite/agent/issues/169 we got the id of the job being processed in the proc title which is great:

```
buildki+ 127817  0.3  0.0 1656068 27100 ?       Sl   19:28   0:01 buildkite-agent v3.0-beta.2 [job 02c039d6]  
```

But I'd love to be able to lookup for that job in buildkite's UI. Am I missing an existing way?

cc @keithpitt

**Comment by keithpitt** [comment]
Hey @casperisfine, you're not missing anything! We actually don't have a way to find the job ID in the UI easily, but we probably should! I just clicked around our UI and can't think of a good place to do it. Can you think of anything?

In saying that though, I think we may actually be removing this proc-title changing behaviour we currently have. The way we do it currently is through a really buggy Go library, and it only works on 64bit linux. Hopefully by the time I come to look at it again, they've fixed some of those issues. I wish Go had a better way of changing the process title!

**Comment by casperisfine** [comment]
> Can you think of anything?

I'm not really good at UI/UX, and honestly I'd be fine with an endpoint that I could craft, and that would redirect me to the build page. e.g. `/jobs/<job_uui> -> /<org>/<project>/builds/<build_id>#<job_uui>`. But yeah it's a bit sketchy.

> we may actually be removing this proc-title changing behaviour we currently have

That's too bad :/ I was about to write a script using `ps aux` to instrument our agents occupancy rate.

Would that be replaced by other way to inspect what an agent is currently doing? (besides tailing the logs).

**Comment by keithpitt** [comment]
We can only put a limited amount of information inside the process title - I haven't thought that far ahead yet of what we might replace it with. We were thinking of allowing the agent to send out statsd events - would something like that work?

**Comment by byroot** [comment]
Yes, statsd is what i would have sent

**Comment by keithpitt** [comment]
We won't be removing the `ps aux` behaviour any time soon I don't think, so you could probably rely on it for a little while longer.

In terms of looking up the Job ID, what about using a GraphQL Query?

```graphql
query {
  job(uuid: "...") {
    url
  }
}
```

You could probably shell something together to make it easier to use as well:

```shell
curl -X POST "https://graphql.buildkite.com/v1" \
  -H 'Authorization: Bearer xxx' \
  -d "{ \"query\": \"query { job(uuid: \\\"...\\\") { ...on JobTypeCommand { url } } }\" }" | jq -r ".data.job.url"
```

**Comment by byroot** [comment]
> You could probably shell something together to make it easier to use as well

Yup, I'd definitely add a script on our servers for easy lookup.

Well, I'm sold!

**Comment by keithpitt** [comment]
Awesome!! 👍
