### ISSUE TITLE
Feature request: pipeline-level access control

### ISSUE THREAD

**Issue by mdub** [buildkite/feedback#165]
Buildkite supports a many-to-many relationship between pipelines and teams, annotated with an access-level. For instance:

"MyTeam" gets "Full Access" to "blahblah"
"Operators" get "Build & Read" on "blahblah-in-prod"
"Everyone" gets "Read Only" on "cool-tool"

Currently, though, this access must be administered via "Team" settings, which is awkward.

Please allow users to manage access to their pipelines as part of the "pipeline settings".

**Comment by keithpitt** [comment]
We have this now! 🚀
