### ISSUE TITLE
Pipeline admins cannot manage access of other teams to their pipelines

### ISSUE THREAD

**Issue by mdub** [buildkite/feedback#166]
I have a user (let's call him "Angus") who has "Full Access" to a pipeline ("CP Pub Ingestor").  Angus wants to be able to see, and potentially change, the access that the "Everyone" team has to that pipeline ... but he can't.

Here's what he sees under ".../teams/everyone":

![screen_shot_2016-06-16_at_09 00 48](https://cloud.githubusercontent.com/assets/610/16101015/dff8f854-33a5-11e6-832a-6196f4b961d0.png)

**Comment by mdub** [comment]
It would be awesome if pipeline admins (i.e. members of teams with "Full Access" to a pipeline) could manage access of _other_ teams to that pipeline ... kind of like GitHub does for repositories:

![screen shot 2016-06-16 at 16 52 13](https://cloud.githubusercontent.com/assets/610/16107914/ea7b3a34-33e2-11e6-9230-c82801eb613a.png)

**Comment by keithpitt** [comment]
Thanks for this feedback @mdub. Before we ship Teams to the world, I'll make sure these things have been addressed.

**Comment by keithpitt** [comment]
Whoops, didn't mean to close :)

**Comment by lsimoneau** [comment]
Any update on this?

**Comment by keithpitt** [comment]
@lsimoneau not yet, but I just wanted to clarify something on this.

Couldn't you make Angus in this scenario a Team Admin? Wouldn't they be able to manage the permissions of other teams then?

**Comment by mdub** [comment]
Do you mean a Team Admin, @keithpitt, or an Org Admin?

We wouldn't want to make Angus an Org Admin ... as we already have too many of those.

Let's ignore the Everyone team for a minute, as it's kind of a edge case.  Instead, imagine teams "A" and "B".

Assume Angus is a member of "Team A", who are primarily responsible for the pipeline in question ("CP Pub Ingestor"). Angus may well be an admin of "Team A", but that's not important right now.

Bob from "Team B" expresses an interest in the project, and Angus (who has "Full Access" to that pipeline) agrees to give them read-only access.  But, he can't make it so, because he's not a member, much less an admin, of Team B (and no, it doesn't seem appropriate to make him so), and as such, can't even see that "Team B" exists.

**Comment by keithpitt** [comment]
👋 This has finally been addressed! Sorry it took so long (permissions are hard). So we've tweaked the logic around "are you allowed to change the teams on a pipeline" to:

- Are you an organisation admin?
- (or if you're not...)
  - Do you have "Manage" permissions on the pipeline
  - Can you see the team that you want to add the pipeline to. "see" can either be through 2 mechanisms:
    - The team has a privacy setting of "visible"
    - Or if the team has a privacy setting of "secret", but you're a part of it

It works exactly like how you describe it here @mdub:

> It would be awesome if pipeline admins (i.e. members of teams with "Full Access" to a pipeline) could manage access of other teams to that pipeline ... kind of like GitHub does for repositories:

In your follow up example @mdub:

> Bob from "Team B" expresses an interest in the project, and Angus (who has "Full Access" to that pipeline) agrees to give them read-only access. But, he can't make it so, because he's not a member, much less an admin, of Team B (and no, it doesn't seem appropriate to make him so), and as such, can't even see that "Team B" exists.

If "Team B" had a privacy setting of "Visible", then this would be possible!

**Comment by mdub** [comment]
Thanks, @keithpitt; I think Angus will be happy.
