### ISSUE TITLE
Consistently sort agent metadata

### ISSUE THREAD

**Issue by shuber** [buildkite/feedback#168]
It doesn't appear to always be consistent when scanning thru the metadata listed on the "Agents" page. For example, the AWS `instance-id` and `ami-id` appear in random order across the different agents.

It made things slightly more difficult when I was trying to scan thru the list to see which agents had updated `ami-id` values after I pushed a change.

**Comment by keithpitt** [comment]
I'll push a fix for this out today!

**Comment by keithpitt** [comment]
I've shipped this @shuber :rock

**Comment by shuber** [comment]
Awesome, thanks @keithpitt!
