### ISSUE TITLE
Artifact details are not updated when artifacts are created

### ISSUE THREAD

**Issue by jnewbigin** [buildkite/feedback#171]
While a build is running, watch the Artifacts tab.
When an artifact is created, a badge is added indicating there is one actifact.
The text remains 'There are no artifacts for this job.'

A reload will show the correct text & link to the artifact.
Tested in Firefox & Chrome

![buildkite1](https://cloud.githubusercontent.com/assets/7644148/17160308/7a1f88b0-53e7-11e6-98f0-0de734bdb058.png)
![buildkite2](https://cloud.githubusercontent.com/assets/7644148/17160314/81ea0dea-53e7-11e6-95c5-041d63477721.png)
![buildkite3](https://cloud.githubusercontent.com/assets/7644148/17160330/995d02ca-53e7-11e6-9ba7-946d167930b2.png)

**Comment by jnewbigin** [comment]
After a reload
![buildkite4](https://cloud.githubusercontent.com/assets/7644148/17160369/d1730fa6-53e7-11e6-89db-a3147286ea1e.png)

**Comment by toolmantim** [comment]
Thanks for the great bug report @jnewbigin, screenshots and all! I've just fixed this for you… no more sad out-of-date artifact tab 😭 

![fixed artifact tab](https://cloud.githubusercontent.com/assets/153/17165208/2718629c-5412-11e6-94b6-fbc77432b201.gif)

**Comment by jnewbigin** [comment]
WooHoo! Thanks for the fast action.
