### ISSUE TITLE
Provide api access to retry individual build job

### ISSUE THREAD

**Issue by josephmbeveridge** [buildkite/feedback#172]
You can currently trigger a full build rebuild via api (https://buildkite.com/docs/api/builds#rebuild-a-build), but there is no way to trigger a retry of a single job inside of a build via api.

This would be awesome as rebuilding the entire build causes more points of failure since each job has a second opportunity to fail, even if the previously failing job passes, and cause another build failure.

**Comment by toolmantim** [comment]
We added this in 1 August 2016 — sorry we forgot to update this ticket @josephmbeveridge! You can find the documentation for this here: https://buildkite.com/docs/rest-api/jobs#retry-a-job

**Comment by josephmbeveridge** [comment]
You actually replied to me via twitter at the time :) I just forgot this issue was still open

**Comment by toolmantim** [comment]
@josephmbeveridge oh, whoops!
