### ISSUE TITLE
Provide limit query param for builds api

### ISSUE THREAD

**Issue by josephmbeveridge** [buildkite/feedback#174]
It would be awesome if there was a `?limit=x` for the builds api (https://buildkite.com/docs/api/builds#list-builds-for-a-pipeline) so that apps which are trying to use less data can receive smaller payloads.

**Comment by toolmantim** [comment]
Hi! You can do this with the `per_page` param: https://buildkite.com/docs/api#pagination (it's a little harder to find in the docs sorry). Let me know if that works as expected for you.

**Comment by josephmbeveridge** [comment]
👌thanks so much
