### ISSUE TITLE
Feature request: 24-hour format

### ISSUE THREAD

**Issue by srs** [buildkite/feedback#176]
I would really like to see 24-hour format of date/time in all views. Or better yet, an option for allowing different type of date/time formats. 

<img width="505" alt="screenshot" src="https://cloud.githubusercontent.com/assets/45278/17449633/34f2c12c-5b5c-11e6-9f7e-60dcad023669.png">

**Comment by keithpitt** [comment]
Hey @srs - thanks for the suggestion! It's not something we've considered in the past. We've tried to keep the timestamps as human-readable as possible. Out of interest, why do you think 24-hour formats would be better in this case?

**Comment by srs** [comment]
In Norway (or almost entire Europe) we are not used to AM/PM format. It's really confusing for us. 24 hour format is probably the only "universal"-format for time.

**Comment by keithpitt** [comment]
@srs thanks for the explanation!

We have the opposite in Australia, where 24 hour time isn't really used (unless you're in the Army :P) . It sounds like in the future we should have an option to support both formats so our times are as accessible as possible to people all over the world!

**Comment by keithpitt** [comment]
(Whoops, didn't mean to close this issue)

**Comment by eik3** [comment]
Please add the option to display times in 24 h format. The 12 h format is very [confusing](https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight). 
In the markup, the time is already properly specified in ISO 8601 format, so it shouldn't be too hard to change the display format on the frontend? 
> `<time datetime="2019-04-02T13:44:59.800Z" title="Tue 2nd Apr 19 at 3:44:59 PM">Today at 3:44 PM</time>`

**Comment by ticky** [comment]
Hey folks! I'm glad to report we've just shipped an update so we're a bit better about this.

We pull the expected time format from your browser's configured locale settings, and honour that wherever we render a time on the frontend.

That means, for instance, if you're configured for `en-AU` like we are, or `en-US`, you'll continue to see 3:44 PM. If you're configured for `en-GB`, `de-DE` or many other locales throughout Europe, we'll now show 15:44. All our times, as before, are in your local system time, but we've always transmitted times in UTC under the hood.

This sadly can't draw from your system's actual 24-hour time preference - the browser APIs don't allow that - but we hope it's a nice step in the right direction. 😄
