### ISSUE TITLE
Feature Request: link to new build form

### ISSUE THREAD

**Issue by TimMoore** [buildkite/feedback#179]
Would be cool if https://buildkite.com/org/pipeline/builds/new worked (or if there were some other way to link directly to a "New Build" form).

Bonus points if https://buildkite.com/org/pipelin/builds/new?build[message]=foo&build[branch]=bar pre-populates the fields :smile:

**Comment by keithpitt** [comment]
We actually support this already :)

https://buildkite.com/org/pipeline#new?message=blah&branch=foo&commit=da-commit

Have a good day!!
