### ISSUE TITLE
"My builds"

### ISSUE THREAD

**Issue by abraham-chan** [buildkite/feedback#184]
Coming from CircleCi I'm mourning the loss of a "My Builds" feature, where you can see the current build status (scheduled, failed etc) of each branch you were involved in. 

Bonus points if it is always visible as a panel for easy switching.

Here's a screenshot of their old design I found on google images:
http://npmawesome.com/wp-content/uploads/2015/01/circle-ci-02.png

**Comment by keithpitt** [comment]
Hey @abraham-chan - this is actually something we have in the works right now :) We've got it behind a feature flag if you're interested! Happy to turn it on for you and your team.

We've still got some UI work to do on it, but it's fully functional!

**Comment by abraham-chan** [comment]
@keithpitt That sounds great, we're happy to be your guinea pigs. 😄

**Comment by keithpitt** [comment]
@abraham-chan done :) Check out the link in the navigation bar. We've got plans to improve the UI for this in the coming weeks. I've also toggled on a beta version of a new pipelines list :)

Will close this now - please shoot me an email at keith@buildkite.com if you have any feedback about anything!
