### ISSUE TITLE
Expose BUILDKITE_AGENT_ID to jobs

### ISSUE THREAD

**Issue by shuber** [buildkite/feedback#185]
Currently it appears that only `BUILDKITE_AGENT_NAME` is exposed as an environment variable. I'd like the hit the "Get an Agent" API endpoint but that requires an `id` not the `name`. Can we please expose the `id` as an environment variable as well?

**Comment by keithpitt** [comment]
Shipped :) I've added `BUILDKITE_AGENT_ID` 👯

**Comment by shuber** [comment]
@keithpitt Awesome! Thanks for the quick turnaround!
