### ISSUE TITLE
Need pull request metadata in post-build webhook.

### ISSUE THREAD

**Issue by bsommardahl** [buildkite/feedback#186]
I'm building a custom notification that makes it easier for devs to navigate to pull requests after they finish building. It would be nice if the pull request number, at least, was included in the payload.

**Comment by camilorivera** [comment]
It will be nice if we could have a boolean too.

**Comment by toolmantim** [comment]
This has been done! API and webhook responses now contain a `pull_request` property containing `id` and `repository` 🎉
