### ISSUE TITLE
Feature request: Invite users to our org with API

### ISSUE THREAD

**Issue by SomeoneWeird** [buildkite/feedback#187]
Would like to automate our onboarding process and this would make it complete, would be cool if we could manage teams etc too.

**Comment by keithpitt** [comment]
@SomeoneWeird would SSO help? We have that!!

**Comment by apparentlymart** [comment]
@keithpitt I can't speak for @SomeoneWeird but SSO sounds pretty interesting to me. I Googled it quickly and the only reference I could find to it was a passing reference at the end of the "Migrating from Bamboo" page. Are there some docs somewhere on how to turn this on?

**Comment by keithpitt** [comment]
@apparentlymart we have SSO available via SAML (Okta, etc) and Google Apps. If you shoot an email through to support, we should be able to help you out :)

**Comment by SomeoneWeird** [comment]
Hey, sorry I missed the notification for this!

SSO would work, but have a bunch of 3rd party contractors that we also give @company.com email addresses to, that we want to invite to specific teams (with less access). So i'm a bit hesitant in turning on SSO globally

**Comment by keithpitt** [comment]
👋 You can now manage users through our GraphQL API. If you head on over to http://graphql.buildkite.com and explore the docs, you'll be able to see the mutations you'll need to run! 🚀
