### ISSUE TITLE
Archive pipelines

### ISSUE THREAD

**Issue by joho** [buildkite/feedback#188]
I was browsing through my pipelines page, and there are a range of old projects that we'd like to hold onto for posterity/audit reasons but not have clutter the day to day. 

As far as I can tell my options are delete or look at it all the time.

**Comment by JuanitoFatas** [comment]
Sorry for the delay 🙇🏻‍♂️ We have added the ability to [Archive Pipelines](https://buildkite.com/changelog/111-archive-pipelines).
Thank you for opening the issue!
