### ISSUE TITLE
Retry successful build steps

### ISSUE THREAD

**Issue by backus** [buildkite/feedback#189]
From the support room:

> **John Backus [3:14 PM]**
> I like that I can retry a single build step if it fails
> Seems like I can't though if it passes
> We had a small issue today though where it looked like one webhook from buildkite didn't make it to github (step was done but github said it was still pending)
> would have been nice to rerun the step instead of the build to trigger the webhook
> 
> **Tim Lucas [3:18 PM]**
> @backus: ah, yeah I can see that. Can you put that in the feedback repo?

**Comment by mkurutin** [comment]
Another use-case for having a Rerun button for successful builds would be a rapid (one click) deploy of a green build. Currently if we want to roll-back a change in production and deploy an earlier version we have to wait for the whole pipeline to run before it comes to the last step which is the deploy.

**Comment by wangdanny** [comment]
any update for this feature? I have an exactly the same use case with @mkurutin. the only difference is that if I run my pipeline again, the artifact created may be changed due to its dependencies may change. so I would like to have the ability to rerun a passed step.

**Comment by danbadge** [comment]
There is a way to workaround this by splitting out the deployment into a separate pipeline and there's an example of it here:
https://github.com/buildkite/polyglot-co-demo-backend/tree/master/.buildkite

This involves using a 'trigger' step and version 3.x of the buildkite agent. The latter enables access to environment variables in your pipeline.yml.

Completely agree with the idea though, being able to re-run a previously passed step would be our preferred method of re-deploy/rollback.

**Comment by a-i-joe** [comment]
![gif](https://media0.giphy.com/media/CvZuv5m5cKl8c/giphy.gif)

**Comment by kunwardeep** [comment]
but when will this feature be prioritised? 😞  Its been over a year 😢

**Comment by lox** [comment]
We're working on this! Should see something early next year.

**Comment by danbadge** [comment]
Great news 👍

**Comment by danbadge** [comment]
Any update on this?

**Comment by jsh2134** [comment]
they just added this feature https://building.buildkite.com/new-in-buildkite-job-retries-3f60a8d45ed2

**Comment by ticky** [comment]
Specifically, you can set [the `permit_on_passed` flag](https://buildkite.com/docs/pipelines/command-step#manual-retry-attributes) mentioned here. :)

**Comment by danbadge** [comment]
Awesome! That works for me :)

Does that mean this issue can be closed?

**Comment by keithpitt** [comment]
@danbadge yup! This is shipped and now part of BK core :)

Thanks for your patience everyone!

**Comment by bradleyess** [comment]
Would be ace to make this default behavior and opt-out via configuration!

**Comment by jtomaszewski** [comment]
Yeah! Can we make it default behaviour?
