### ISSUE TITLE
Question / Feature Request: Ability to get data on build pipeline health

### ISSUE THREAD

**Issue by DamonOehlman** [buildkite/feedback#195]
We have quite a few flakey steps in our build (that we are trying to get sorted), but some of them are particularly stubborn.  None of these are the fault of buildkite (as I'm sure you're aware), but we would love to get some insight on the steps that fail and on a retry action magically work again to help identifying the main culprits.

I've been working with improving the build over the last few weeks so have a pretty good idea about this, but longer term I think this will be important for us to be able to keep on top of our build processes and understand points of weakness.

**Comment by keithpitt** [comment]
@DamonOehlman we have something _close_ to this launching soon. If you DM me on the Buildkite Chat Slack I'll show you what we've got so far :)
