### ISSUE TITLE
Visual cue for build step blocked on concurrency rules

### ISSUE THREAD

**Issue by DamonOehlman** [buildkite/feedback#197]
At the moment in the UI a build step that is blocked due to concurrency rules will look like an build step that hasn't been able to find an agent to complete the step (i.e. reports "Waiting for agent" I think).  Would be great if this flagged in the UI that it was waiting for a concurrency group to become free.  I was scratching my head for quite a few hours yesterday trying to work out why an agent wasn't picking up a job.  Finally removed the concurrency group on a hunch and found out why :)

**Comment by keithpitt** [comment]
@DamonOehlman ah! Yes...I want this as well. I've also been tripped up by that as well (luckily I have DB access to see what's going on).

I think having a visual cue for this would be a really nice addition to the UI!

**Comment by keithpitt** [comment]
👋 This took a little while, but if you head on over to the "Agent" tab when a job is blocked on concurrency rules, it'll tell you that it's blocked on a concurrency rule. Sorry it took so long to get out!

**Comment by DamonOehlman** [comment]
No worries Keith - thanks heaps for implementing it, will head over the UI now and see if I can spot it in action :)
