### ISSUE TITLE
Feature request: Render URL text in build logs as hyperlinks

### ISSUE THREAD

**Issue by samueljamesmarshall** [buildkite/feedback#198]
Currently, we output links in our build logs for CodeDeploy deployments, code coverage reports etc..

Because I'm a lazy human being, copying link text from the log into my browser address bar is too much for my whining self.

JavaScript example of what could be done:
```javascript
let tableRowString = " blah   https://ap-southeast-2.console.aws.amazon.com/codedeploy/home?region=ap-southeast-2#/deployments/d-A1GPS190I      meh ";
let start = tableRowString.indexOf("http");
let end = tableRowString.indexOf(" ", start);
let url = (end == -1) ? tableRowString.slice(start) : tableRowString.slice(start, end);
let element = `<a href="${url}">${url}</a>`;
let newTableRowString = tableRowString.replace(url, element);
```
The above may be of no use to you, but I thought I'd share :simple_smile:

**Comment by sj26** [comment]
I hate copy/pasting like that, too! We didn't want to tread on toes by linking everything that looks kinda like a link, though. Maybe we should! We'll consider it.

In the meantime, we do support linking from your terminal output:

https://github.com/buildkite/terminal#links

By outputting escape codes around the URL we'll turn it into a link for you. You can even change the displayed text versus the URL.

Here's an example in Ruby that we use which only links when we know it's going to a Buildkite log:

```ruby
def link_to(url, content = nil)
  if ENV["BUILDKITE"]
    "\e]1339;url=#{url.gsub(";", "%3b")}#{";content=#{content.gsub(";", "%3b")}" if content}\a"
  else
    url
  end
end
```

**Comment by keithpitt** [comment]
I'm going to close this since we support embedding links in build logs already. Thanks for submitting the issue @samueljamesmarshall! Sounds like we may need to increase the visibility of that documentation :)

**Comment by marcelas** [comment]
How is the equivalent in java script? I've tried console.log(` \u001b]1339;url=${url}\a\n`); but it didn't work

**Comment by sj26** [comment]
@marcelas try with hex escape codes: `console.log(`\x1b]1339;url=${url}\x07`);`

**Comment by marcelas** [comment]
@sj26 both seem to work on the buildkite standalone terminal, but neither work on the actual interface at bildkite.com. It seems related to the url I am using

**Comment by sj26** [comment]
@marcelas oh dear — sorry it's not workin! Would you mind sending us an email with a link to a build showing the problem so we can take a look? support@buildkite.com

**Comment by shardulsrivastava** [comment]
@sj26 whats the equivalent of showing the links in logs for bash ??

**Comment by sj26** [comment]
@shardulsrivastava if you're using a modern terminal emulator like iTerm 2 then these terminal escape codes should result in clickable links in your terminal. Otherwise you might like to detect the terminal and output the url in parens or something instead/as well.

**Comment by snoblenet** [comment]
I'm using the form `\x1b]1339;url=${url};content=${content}\x07`; but I'm getting the error `Parsing error: Expecting Unicode escape sequence \uXXXX`. [The Eslint documentation](https://eslint.org/docs/rules/no-octal-escape) says "As of the ECMAScript 5 specification, octal escape sequences in string literals are deprecated and should not be used. Unicode escape sequences should be used instead." Suggestions?
