### ISSUE TITLE
Dynamic updates of pages are unreliable

### ISSUE THREAD

**Issue by notahat** [buildkite/feedback#20]
I often leave a page open showing running builds (either for a whole project or a branch), and it seems to update unreliably. Sometimes a build will look like it's been running for ages, and a refresh will show that it finished a while ago. Often new builds on the branch won't appear on the page without a refresh.

(This is all on Safari 7.0.4.)

**Comment by keithpitt** [comment]
I'm going to close this now because I think most of those problems have been squished! There are some known issues around the back button, but we'll hopefully be able to fix those soon :D:D :dancers:
