### ISSUE TITLE
Ability to block a job from being retried

### ISSUE THREAD

**Issue by apparentlymart** [buildkite/feedback#200]
We have a small set of non-idempotent pipeline steps that are not safe to "Retry" when they fail. Instead, the user needs to "Rebuild" the whole pipeline to run some other steps that need to be repeated first.

Currently we have these jobs set up to "feign success" when they fail. That is, they print out "I failed!" in the log but still exit with status zero to prevent Buildkite from showing the "Retry" button. However, since it's buried in the log output often we don't notice it and assume the pipeline succeeded.

It would be handy to have a way to tell buildkite that once a job has reached a certain point it's no longer safe to retry on failure, so that we can still complete with a non-success status but not show the "Retry" button.

(Originally we tried to solve this with training, but it was hard for people to remember which jobs were safe to retry and which ones weren't, so we decided to try to solve with technology instead.)

---

In case you're interested, the real use-case here is that we use [Terraform](https://terraform.io/) for deployment and we split Terraform's "plan" phase and "apply" phases into separate pipeline steps separated by an approval block. If "apply" fails then it may have partially changed the world and so it's necessary to re-run the "plan" step to make a fresh plan that considers any changes that _did_ succeed on the previous run. I'd be happy to hear other suggestions on how to solve that problem. :grinning:

**Comment by keithpitt** [comment]
@apparentlymart ah yes, we've had pretty much this discussion internally before. Sometimes there a build jobs that you just _never_ want re-run for multiple reasons. @sj26 has mentioned this before a few times as well.

Being able to turn off "retries" for a job is something that we gotta have! How's this for a syntax?

```
steps:
  - command: "fail-then-succeed.sh"
    retries:
      manual: false
```

**Comment by sj26** [comment]
Maybe a simple shortcut syntax, too?

```yml
steps:
 - command: "fail-then-succeed.sh"
   retries: false
```

**Comment by keithpitt** [comment]
@sj26 I'm thinking of allowing `automatic` retries in the future (which is why I figured under the `manual` key could work) https://github.com/buildkite/agent-tests/blob/master/tests/retryable-commands/.buildkite/pipeline.yml

But I suppose `retries: false` would work as well!

**Comment by sj26** [comment]
I like `retry` (singular) as a key better, per your linked example! And I think `retry: false` works well as a shortcut for `retry: {automatic: false, manual: false}`, same as `- block: "Button"` is short for `- {type: block, label: "Button"}`, etc.

**Comment by keithpitt** [comment]
Sounds good to me!

**Comment by apparentlymart** [comment]
This all sounds good to me too! 😎

**Comment by keithpitt** [comment]
👋 sorry for such a late reply to this - but it's a thing now! https://buildkite.com/docs/pipelines/command-step#manual-retry-attributes

```
steps:
  - command: "fail-then-succeed.sh"
    retry:
      manual: false
```

allows you stop retries from happening on a particular step 🚀
