### ISSUE TITLE
Password confirmation dialog for SSO users?

### ISSUE THREAD

**Issue by lsimoneau** [buildkite/feedback#202]
I log into Builldkite via Okta SSO, but when trying to generate API tokens I get a dialog asking me to "Confirm password to continue"...

<img width="375" alt="screen shot 2016-10-19 at 4 28 12 pm" src="https://cloud.githubusercontent.com/assets/31768/19506669/46878830-9619-11e6-94ae-6891470ce6b8.png">

**Comment by lsimoneau** [comment]
Hello? Still can't get API tokens.

**Comment by keithpitt** [comment]
@lsimoneau will ping you on Slack!
