### ISSUE TITLE
Pull-request builds (sometimes) incorrectly grouped under "master" branch

### ISSUE THREAD

**Issue by mdub** [buildkite/feedback#203]
This is easiest to describe with an example:

![builds](https://cloud.githubusercontent.com/assets/610/19507474/f5b6a71e-961e-11e6-9548-3d7dcf5b7b3e.png)

Buildkite has grouped commit 21bfd81 under "master", as though it's on the mainline, when in fact it's the head of an un-merged pull-request.

The problem extends to cc.xml feeds, too.

**Comment by mdub** [comment]
Additional info: the pull-request came from the "master" branch _of a fork_.

My assumption/desire is that the "master" group would only represent the master branch of the configured Git repo.

**Comment by keithpitt** [comment]
Ahhh, I see what's happening now.

It sounds like this page may need to become "fork-aware". Or maybe it shouldn't show forked builds at all like you suggested?

This page hasn't really kept up with some of the latest features, so it's definitely due in for a re-think (we've recently prettied it up a little bit though)

**Comment by chrislloyd** [comment]
We had exactly the same situation happen. Perhaps just having the branches be identified by their full repo url rather than just the ref name would be more accurate?

**Comment by lox** [comment]
My preference would be to group them as `user:branch` if they are merge requests from forks.

**Comment by mdub** [comment]
Nice idea, @lox.  Bonus points if the solution also allows us to whitelist builds based on fork/user.

**Comment by lox** [comment]
You could do that with a wait step couldn't you?

**Comment by toolmantim** [comment]
We've just rolled out changes to fix this!

For all new pipelines, it defaults to `user:branch` for builds from forks.

For all existing pipelines you'll need to turn it on in your pipeline’s GitHub settings:

<img width="891" alt="add-an-option-for-third-party-fork-prefixing" src="https://user-images.githubusercontent.com/153/26864849-8ca28e3e-4b9d-11e7-9bbc-49abab5aa948.png">

❤️
