### ISSUE TITLE
[feature] API endpoint to check if an array of commits is green

### ISSUE THREAD

**Issue by therealbnut** [buildkite/feedback#205]
### Problem

We would like to run our CI against a diff, rather than run all our tests every time.
### Current Solution

At the moment we're trying to find the commit range that needs to be tested by a build. We want to use this with dynamic build pipelines to run a subset of our tests that are relevant to the changes (possibly none of them).

It's necessary to know the range of commits rather than just run it on the diff of the current commit. For example, if the previous commit was a failure, but the next commit changes unrelated code. In this case a single commit diff will result in a passing test, despite the problem not being fixed.

To do this we need to know the most recent passing commit in a branch's git history, currently the best way to do this seems to be:

```
"${BUILDKITE_API}/organizations/${ORG_NAME}/pipelines/${PIPELINE}/builds?
    branch=${BRANCH_NAME}&state=passed&per_page=1"
```

However there are a few issues with this:
- the order of results are based on when they were built, not the git ancestry of the commit
- only commits in this branch will be returned, not ancestors
- the MERGE_HEAD isn't known on the build machine, there may be several if it's a staging branch

To do this properly with the current API would be very expensive, and fragile, we would:
- remove the `branch=` filter, which will search every build
- search multiple pages of results, possibly a lot
- specify a timestamp to make it scale better, but that is susceptible to synchronisation issues
- cross reference commits in the response with the current branch's commit history
### Desired solution

Ideally we'd like to be able to send an array of commit hashes to an endpoint, then have the endpoint return an array of build statuses. It would be fine if it just returned the first "passed" commit in that array.

For example:

**Request**

``` http
GET https://api.buildkite.com/v2/MyCompany/pipelines/MyPipeline/builds
  ?commit[]=25a1979fafb6113535eaee3d6e8df960fbee4306
  &commit[]=8cade0a243b395de7cf3648f9c77a69782bfd4de
  &commit[]=958b93c910d4b0645e0c220dc8e01f3ee5986290
  &commit[]=381427d222d774406afc41212bb33a99e7b6cd31
```

**Response**

``` json
[
    {"commit": "381427d222d774406afc41212bb33a99e7b6cd31", "status": "scheduled"},
    {"commit": "958b93c910d4b0645e0c220dc8e01f3ee5986290", "status": "running"},
    {"commit": "8cade0a243b395de7cf3648f9c77a69782bfd4de", "status": "failed"},
    {"commit": "25a1979fafb6113535eaee3d6e8df960fbee4306", "status": "passed"}
]
```

**Comment by keithpitt** [comment]
Hey @therealbnut - I've got a solution for you!

So you've probably seen that we've recently released a GraphQL API, using that should make this easy :)

Here's a query for you:

```graphql
query {
  pipeline(slug: "MyCompany/MyPipeline") {
    builds(first: 10, commit:["eb81c509e5c11f3f7673e34ec6d85d7d41919cd9", "41613d7dd37f5196ffc6f308769de06fef3d5bb9"]) {
      edges {
        node {
          commit
          state
        }
      }
    }
  }
}
```

Returns this:

```json
{
  "data": {
    "pipeline": {
      "builds": {
        "edges": [
          {
            "node": {
              "commit": "eb81c509e5c11f3f7673e34ec6d85d7d41919cd9",
              "state": "passed"
            }
          },
          {
            "node": {
              "commit": "41613d7dd37f5196ffc6f308769de06fef3d5bb9",
              "state": "passed"
            }
          }
        ]
      }
    }
  }
}
```

This query will return all the builds that match those commits. You can further scope the builds to a particular state like so:

```graphql
builds(first: 10, state: [BUILD_STATE_PASSED, BUILD_STATE_FAILED], commit:["eb81c509e5c11f3f7673e34ec6d85d7d41919cd9", "41613d7dd37f5196ffc6f308769de06fef3d5bb9"]) {
```

If you just wanted to get the passed/failed builds. You should be able to use that response to figure out what you need.

You can find more about how to use our GraphQL over here: https://building.buildkite.com/tutorial-getting-started-with-graphql-queries-and-mutations-11211dfe5d64

I hope this helps!

**Comment by therealbnut** [comment]
Nice, thanks :) I had a look at your GraphQL, but it didn't seem to allow `commits:`, is this new?

**Comment by keithpitt** [comment]
@therealbnut yeah, it's pretty new. As of about 20 minutes when I added it just for this :)

**Comment by therealbnut** [comment]
Haha, nice - thank you :) I imagine it will be useful in lots of other use cases as well

**Comment by keithpitt** [comment]
If you end up finding other stuff in GraphQL you want, just let me know! It's generally pretty easy to as since we're still building out our GraphQL schema.

**Comment by therealbnut** [comment]
Cool, will do - thanks for the help!
