### ISSUE TITLE
Manual override environment variables defined in pipeline

### ISSUE THREAD

**Issue by wvanbergen** [buildkite/feedback#208]
If you have an environment variable defined for a pipeline, setting the same variable when triggering a manual build will not overwrite the value.

We use ENV variables to version our bootstrap script. It would be nice to test new versions on a single build, instead of having to update it for the pipeline and immediately affect all builds.

**Comment by keithpitt** [comment]
@wvanbergen that's how it should be working, maybe there's a bug! How are you declaring the base environment variables?

**Comment by wvanbergen** [comment]
We normally have set the `RUNNER_VERSION` variable in the Settings UI of our pipeline. We have only one step defined, Configure. Configure will generate a pipeline file and replace the current pipeline with it. The generated pipeline can override `RUNNER_VERSION` for either a single, or all the subsequent steps. This way, we can easily test a new version by generating a pipeline with a new version and see if it works.

This doesn't apply to the configure step itself though. As a way of testing new versions of the "configure step, I was hopping I would be able to specify a `RUNNER_VERSION` in the "Trigger build" UI.

![screen shot 2016-10-31 at 9 10 13 am](https://cloud.githubusercontent.com/assets/15870/19855243/e1d9cf80-9f49-11e6-870b-3dfab75d603c.png)

However, this does not seem to override the value set in the Settings UI of the pipeline.

**Comment by keithpitt** [comment]
Oh right, I see now @wvanbergen :) To be honest, I actually thought that's how it worked, but after checking the code I can see the order of environment variable merging is this:

- Project environment
- Build environment
- Step environment

When you manually trigger a build, you're setting the "Build environment" data, so in this case it's being overriden by the "Step environment".

I've just opened a PR internally to change the behaviour, I'll need to get some feedback from the team to see if this something we can/should do.

Thanks for submitting this bit of feedback!

**Comment by keithpitt** [comment]
@wvanbergen 🚀 I've just pushed a change to production so you'll be able to override Environment Variables using that Trigger Build UI.

Let me know how it goes! 💃

**Comment by wvanbergen** [comment]
it works 🎉

**Comment by keithpitt** [comment]
Excellent! :D
