### ISSUE TITLE
Validate pipeline.yml

### ISSUE THREAD

**Issue by christophermaier** [buildkite/feedback#212]
When uploading a `pipeline.yml` file as part of a pipeline, it would be good if the step failed with invalid YAML.

Just now, we realized our concurrency settings were wrong because we misspelled "concurrency" in our yaml file. If the invalid file were flagged as such and failed the build immediately, we could have fixed it.

**Comment by keithpitt** [comment]
@christophermaier I've had that exact problem before! It's an easy mistake to make.

In the 3.0 Beta, we validate the file to see if it's valid YAML, but we don't do any linting or validation of the properties that are uploaded. I think it's a good idea! I'll pass this feedback along to the team and we'll see what we can do soon!

**Comment by diist** [comment]
Happens to us as well, for example it's easy to type in `branch:` instead of `branches:` and very hard to troubleshoot.

**Comment by keithpitt** [comment]
@christophermaier @diist I just pushed a fix that should avoid this situation in the future! We now validate which keys you send, and make suggestions.

So in your example @diist it'd say: "hey, `branch` isn't a thing, but maybe you meant `branches`?"

Thanks for the feedback! 💃

**Comment by christophermaier** [comment]
@keithpitt Fantastic, thanks!
