### ISSUE TITLE
Add hook to run after job cancellation

### ISSUE THREAD

**Issue by hamstah** [buildkite/feedback#214]
Hi,
I'm using a post-command hook to clean up resources like docker containers.
I need a hook to be able to run it when jobs get cancelled too (either manually or because a new build started).
The containers are namespaced with the job id, so I can't easily kill them in a separate pre-command or similar (I'd need to know all the running jobs to filter them out).

Thanks

**Comment by keithpitt** [comment]
@hamstah yeah, we've been wanting something similar to this for a while! Essentially a "cleanup" type step that runs no matter if the previous stage of a pipeline passes/fails. We don't have that ability just yet in the pipelines, but it's something we're _very_ keen to add!

**Comment by hamstah** [comment]
Ok cool, good to know it's on the roadmap somewhere.

**Comment by toolmantim** [comment]
Yep, this should be handled by the `pre-exit` hook. Thanks @petemounce!
