### ISSUE TITLE
Include retry count in job.* webhooks

### ISSUE THREAD

**Issue by wvanbergen** [buildkite/feedback#216]
This would save us from having to do an API call for every job webhook.

**Comment by keithpitt** [comment]
Hey @wvanbergen - this should be possible! Which API call are you using at the moment to grab the retry count? Are you looking in the ENV var?

**Comment by wvanbergen** [comment]
Yup, we're using the job/env endpoint.

**Comment by wvanbergen** [comment]
Our use case is primarily retrying certain failed jobs automatically. We don't want to endlessly retry jobs that are failing so having access to this data is important.

**Comment by toolmantim** [comment]
We've just added this for you now, you'll find them in the webhook payloads as `retries_count` 👍

**Comment by wvanbergen** [comment]
:tada:

**Comment by tduffield** [comment]
It would be awesome if this was documented on the main site :)
