### ISSUE TITLE
Add the ability to poll job history for a given build agent

### ISSUE THREAD

**Issue by npaufler** [buildkite/feedback#217]
It would be very useful to be able to view what jobs have run on a given build agent, either via the web interface, or via the API.

In our case we autoscale our build agents so they are transient. We're trying to identify a common failure case where a job run on an agent prevents future ones from running. If we could easily view what jobs ran on that agent before it stopped we might be able to start to identify patterns.

It would also be nice if you could view these for disconnected agents as well (in our case, the lifecycled ones part of our autoscaling stack).

**Comment by keithpitt** [comment]
@npaufler totally :) We've been wanting to add this forever... Keep an eye out, hopefully we have something for you soon!

**Comment by keithpitt** [comment]
Job history for an agent is now available via our GraphQL API:

```
query {
  agent(uuid: "..") {
    jobs {
      edges {
        node {
          state
          command
        }
      }
    }
  }
}
```

We haven't added it to the UI yet, but you can grab it in the API if you need to!
