### ISSUE TITLE
Pushing a new branch with no commits runs build against last commit in base branch

### ISSUE THREAD

**Issue by ineffyble** [buildkite/feedback#218]
To replicate:
`git checkout master

  git checkout -b empty

  git push --set-upstream origin empty`

A new build will be created on BuildKite, but will be testing the last commit, which is not new/not unique to the branch.

**Comment by ticky** [comment]
As discussed in Slack, this functionality is working as expected. Builds must match on sha, branch and be from Webhooks in order to be considered the same, as any one of those being different could trigger different behaviour in your build!
