### ISSUE TITLE
API doesn't understand timezones :watch: :eyes:

### ISSUE THREAD

**Issue by ineffyble** [buildkite/feedback#219]
The API docs state that [datetimes should be given in ISO :eight: :six: :zero: :one:](https://buildkite.com/docs/rest-api/builds#get-a-build) format 📅 . The string generated by Ruby in ISO 8601 for right now is 🕚  `2016-11-24T23:23:41+11:00`, which includes the time in Melbourne, and the offset.

When I query for [builds created in the last hour in that format](https://api.buildkite.com/v2/builds?created_from=2016-11-24T22%3A23%3A41%2B11%3A00), I get no results, which is incorrect 🙀 

If I query for [builds created in the last hour with the UTC time](https://api.buildkite.com/v2/builds?created_from=2016-11-24T11%3A29%3A46Z), with a Z (like docs) or [+00:00 offset](https://api.buildkite.com/v2/builds?created_from=2016-11-24T12%3A29%3A46%2B00%3A00), I see the correct results 🤔 

If I take the UTC time from above, and change the offset to +11:00, I see identical results 🔥 ⏱ 🔥

**Comment by ineffyble** [comment]
@ticky I blame you for my recent spike in Emoji usage 😾

**Comment by ticky** [comment]
I’ve got a fix for this in the pipeline 😉
