### ISSUE TITLE
Make timeout available as environment variable

### ISSUE THREAD

**Issue by wvanbergen** [buildkite/feedback#222]
It would be nice if we could know when a job will timeout from inside the job, so we could potentially exit ourselves before that happens, either gracefully, or with a more instructive error message.

**Comment by keithpitt** [comment]
@wvanbergen I've shipped this for you :) `BUILDKITE_TIMEOUT` will now contain that timeout value! I've updated https://buildkite.com/docs/builds/environment-variables to show the new variable.

Thanks for the suggestion!
