### ISSUE TITLE
No links for 'trigger' steps

### ISSUE THREAD

**Issue by lxfontes** [buildkite/feedback#224]
<img width="412" alt="screen shot 2016-12-13 at 11 32 13 am" src="https://cloud.githubusercontent.com/assets/35205/21148997/04019322-c128-11e6-96b3-7b41557a5abe.png">

Scenario:
- `builds` page ( `https://buildkite.com/org/pipeline/builds` )
- 'Configure' is a `command`
- 'Build Container' is a `trigger` (  like https://github.com/buildkite/agent-tests/blob/master/tests/trigger-pipeline/.buildkite/pipeline.yml )
- 'Rebase Check' is a `command`

We see proper links for 'Configure' and 'Rebase Check', but not for 'Build Container'

**Comment by keithpitt** [comment]
Ahhh yes! The UI for that is less than ideal. `trigger` steps still haven't been "shipped", so when we officially make the announcement for them, I think we'll probably clean up the UI for it a lil'bit!

Thanks for the reminder though!

**Comment by toolmantim** [comment]
Good news, the trigger steps now have a permalink in the pipeline! It was released quite a while ago, but we forgot to update this issue. Sorry for the delay there 🙏🏼
