### ISSUE TITLE
Display if a pipeline is running a build on the pipeline index page

### ISSUE THREAD

**Issue by jordie23** [buildkite/feedback#227]
As per the image I've attached. At the moment on the pipeline index page, you can see which pipelines have passed and failed, but not which have a build in progress. Well, not easily. It shows as the latest build in yellow in the bar graph, but that can be small and hard to see if you wish to glance at the page and see what's currently running.

I propose using the icon next to the pipeline to signify if there is a build running.

![pipelines](https://cloud.githubusercontent.com/assets/712360/21558076/c8c1d182-ce88-11e6-9b8d-9df8bbd72d63.png)

I think the old version of this index page displayed if a pipeline had a build in progress similar to this?

**Comment by jordie23** [comment]
A bit more context: We have about 40 pipelines and some pipelines trigger other pipelines, so that's why there's a need to be able to quickly glance and see what's running.

**Comment by keithpitt** [comment]
@jordie23 thanks for the feedback! We've had some similar feedback on this as well. We're just collating all the feedback now and we're planning on pushing out some updates to this page in the new year. Thanks again for taking the time to submit this issue! 👌

**Comment by cammm** [comment]
Yes please!

**Comment by keithpitt** [comment]
I'm happy to report I've just updated the Pipelines List to do this exact thing :) If you've got a running build on your default branch (e.g. `master`, it'll show it in the UI)

Thanks for the suggestion!

**Comment by jordie23** [comment]
You're amazing, thank you!

**Comment by keithpitt** [comment]
<3
