### ISSUE TITLE
Blocked Pipeline Unblock Data

### ISSUE THREAD

**Issue by jufemaiz** [buildkite/feedback#230]
Ref: https://github.com/buildkite/feedback/issues/213#issuecomment-275977898

```
As a buildkite-agent,
I want to have access to who unblocked a blocking step,
So I can use this information in the subsequent steps
```

Use cases include:
* Providing support for permissions (e.g. only certain users can unblock a step);
* Using that information in other systems (e.g. bot notifications direct to individuals at the completion of subsequent steps)

Obviously there's some issues with permissions (e.g. fail it, but the details are then in the branch if using pipeline.yml and hence they'll allow it on retry, though hopefully from a process perspective the failed build should raise eyebrows).

Current workaround recommended by @keithpitt:

> The only way to find out at the moment is to figure out where the current job is in the pipeline using the `BUILDKITE_JOB_ID` env var, then work backwards until you find a block job, then inspect the `unblocked_by` on that.

**Comment by keithpitt** [comment]
Thanks for submitting this @jufemaiz! Those use cases sound like stuff we've bumped into ourselves before. Is one of those cases the problem you're trying to solve at the moment?

**Comment by jufemaiz** [comment]
@keithpitt we've just hit one area where I would like to ensure that there is an authorised list of users able to unblock (in our case it's infrastructure via terraform builds, but we will have another in the coming months which is around delivery of a complete platform for partners, which needs a commercial sign off so we don't want to have unauthorised users hitting go).

We'd also like to be able to use the details of the user who unblocked it to notify them directly, notify the head of product/infrastructure and notify myself that person X has unblocked a step.

**Comment by keithpitt** [comment]
@jufemaiz cool cool - thanks for explaining for me!

Is the work around working OK for the moment? (Even thought it's a little yucky)

**Comment by jufemaiz** [comment]
@keithpitt haven't quite implemented it yet, still designing it :)

**Comment by keithpitt** [comment]
No worries :) Lemme know how it goes!

**Comment by ineffyble** [comment]
This sounds pretty neat, we're starting to look at using Buildkite with Terraform and would definitely value this functionality.

**Comment by toolmantim** [comment]
We've just added the environment variables ​`BUILDKITE_UNBLOCKER`, `BUILDKITE_UNBLOCKER_UUID` and `BUILDKITE_UNBLOCKER_TEAMS` to build jobs after a block step 🎉
​https://buildkite.com/docs/pipelines/environment-variables

**Comment by SEAPUNK** [comment]
I see it in the documentation, and I tried to use this, but it's not showing up? I unblock a step, but the environment variable doesn't show up in the job that comes after the block.

**Comment by ticky** [comment]
@SEAPUNK that’s odd, it should be there - do you want to [shoot Support an email](https://buildkite.com/support) with a link to the build you’re seeing this happen in?

**Comment by SEAPUNK** [comment]
Yeah, I contacted support, and they fixed it. Thanks!
