### ISSUE TITLE
Different colour for jobs that did not run with wait step

### ISSUE THREAD

**Issue by eredi93** [buildkite/feedback#236]
when you use a wait step and a job fails all the jobs after the wait step becomes red, the sam colour of the failed test.
it is missing the `x` that identifies the failed job but to many people, it is quite confusing as it has the same colour of the failed job.
would be better to have a different colour that makes it easier to understand what failed.
I propose grey.

example form the slack discussion https://buildkitechat.slack.com/archives/support/p1489598831619588:
![image](https://cloud.githubusercontent.com/assets/10990391/23970413/92e7cb6a-09c1-11e7-968e-324559fa1571.png)

**Comment by keithpitt** [comment]
Ah, yeah this is good feedback! It's definitely not the first time we've been tripped up on this :)

Maybe for subsequent steps that aren't run, perhaps they should be a light grey red or something? What do you think @toolmantim?

**Comment by toolmantim** [comment]
That's really good feedback, thanks @eredi93! I think grey for anything that hasn't run makes the most sense. We'll look at getting this changed for you.

**Comment by ticky** [comment]
Pasting chat log here;
>----- March 15th -----
>matt 
> [10:27 AM]  
>So, I was under the impression that a “wait” step waited until all previous steps had passed, before continuing, but it seems it continues even if some preceding steps fail…?>
>
>[10:27]  
>![https://cl.ly/0b360a3K0b0T](https://cl.ly/0b360a3K0b0T/Image%202017-03-15%20at%205.26.25%20pm.png)
> Shared with CloudApp
>Image 2017-03-15 at 5.26.25 pm.png (92kB)>
>
>
>Jacopo Scrinzi 
> [10:42 AM]  
>if you look at the jobs after the wait step they did not actually run. if a job fails any job after the wait command will be red>
>
>matt 
> [10:42 AM]  
>ohhhh>
>
>[10:42]  
>derp>
>
>[10:42]  
>thanks that makes sense>
>
>Jacopo Scrinzi 
> [10:43 AM]  
>i know is kinda confusing, that should probably be a different colour from the failed command>
>
>matt 
> [10:43 AM]  
>I guess that’s why there’s no cross>
>
>Jacopo Scrinzi 
> [10:43 AM]  
>@keithpitt possible feature request?>
>
>[10:44]  
>it is confusing if you are new to buildkite, i see my colleges come with the same question

**Comment by eredi93** [comment]
@ticky is this now fixed? why did you close it?

**Comment by ticky** [comment]
because I referenced it in a particular commit… :wink:
<img width="626" alt="screen shot 2017-05-08 at 3 09 52 pm" src="https://cloud.githubusercontent.com/assets/282113/25827512/704b5360-3400-11e7-93ba-c73094c1c61b.png">

**Comment by ticky** [comment]
It’s live! :sparkles:
