### ISSUE TITLE
API: return pipeline descriptions

### ISSUE THREAD

**Issue by joscha** [buildkite/feedback#237]
We query the pipelines endpoint, e.g.
`/v2/organizations/org/pipelines` to get more information about pipelines as we need this for a webhook that allows us to spin up on-demand builds in pull requests (cc @toolmantim).

I noticed that the pipeline description is missing from the returned JSON. Any chance that field can get added?

**Comment by toolmantim** [comment]
I've updated those pipeline responses for you! They now include a `description` property. 

I'll leave these open whilst I get the docs updated too.

**Comment by joscha** [comment]
Awesome, thank you very much!

**Comment by joscha** [comment]
This is up and working.
