### ISSUE TITLE
No descriptive/sharing metatags on Buildkite.com

### ISSUE THREAD

**Issue by ineffyble** [buildkite/feedback#242]
So, BuildKite.com doesn't have any meta tags for sharing (e.g. Open Graph, Twitter Cards, etc), or even a meta description tag.

This means you get an inconsistent and uncontrolled description/preview.

For example, on Facebook:
![image](https://cloud.githubusercontent.com/assets/834880/24499477/9937b9d0-158d-11e7-8b1a-b4d4503051da.png)

You get a decent description, but an unintended image.

You don't get anything on Twitter which requires a card metatag to preview at all, or on several other services designed to use social metadata (Slack, iMessage, etc).

Even Google is showing scraped text, which isn't the best succinct description of the service:

![image](https://cloud.githubusercontent.com/assets/834880/24499502/afa6cc6a-158d-11e7-8291-848a46c55fb3.png)

**Comment by keithpitt** [comment]
We totally need to up our SEO game - thanks! I'll let the team know :)
