### ISSUE TITLE
Ability to specify custom agent targeting rules when manually creating build

### ISSUE THREAD

**Issue by ineffyble** [buildkite/feedback#245]
It would be great if when manually creating a new build (via New Build button on frontend, or API), you could override or add agent targeting rules, for that specific build.

For example, it would let me easily run a particular/once-off build on my laptop, without having it in the default queue or have all builds on a pipeline run there.

**Comment by dtruong0** [comment]
As a work around 
Custom agent targeting can be done through environment variables when you upload your pipeline 
 
In your pipeline.yml have 
```
  - name: 'Test'
    command: scripts/buildkite/test.sh
    agents:
      queue: __QUEUE__
```
In your pipeline.sh have 
```
cat .buildkite/pipeline.yml | sed -e "s/__QUEUE__/$QUEUE/g"
```

In your pipeline upload command 
```
.buildkite/pipeline.sh | buildkite-agent pipeline upload
```

Then the QUEUE environment variable can be used to select you're queue

**Comment by keithpitt** [comment]
Oh! this can be done now with: https://forum.buildkite.community/c/beta-support-feedback/yaml-pipeline-steps

You can define a pipeline like this...

<img width="506" alt="image" src="https://user-images.githubusercontent.com/25882/49001660-551bac00-f198-11e8-8c18-d086813240ef.png">

This will create the first step using a QUEUE value of `default`. If you go over to "New Build" and do something like this:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/25882/49001696-72507a80-f198-11e8-9b4c-839b98014b00.png">

You'll be able to override the queue used by the build. Hopefully this helps! 🚀
