### ISSUE TITLE
Pipelines page uses lots of system resources

### ISSUE THREAD

**Issue by twe4ked** [buildkite/feedback#247]
Our pipelines page seems to pin one of my CPU cores at 100% - any chance we could get pagination of some description put on the roadmap please?

Also, the main reason I come to this page is actually to see the histogram and build stats. It would be awesome to get those at the top of the builds page for a branch.

![screen shot 2017-04-07 at 9 21 32 am](https://cloud.githubusercontent.com/assets/71970/24779806/f3b5722e-1b75-11e7-9e66-206aedfb5557.png)

Cheers

**Comment by twe4ked** [comment]
I haven't seen our graphs load in quite a while now. I think they take longer than I can be bothered to wait. Not a huge worry but it would be a nice to have.

**Comment by ticky** [comment]
HI @twe4ked, I just deployed a change which makes the pipelines page load a smaller number of pipelines on launch. Could you let me know how it performs? Just in case I wasn’t aggressive enough. :smile:

**Comment by twe4ked** [comment]
Thanks @ticky it's actually loading now. Still takes about 10 seconds (with a very **un**scientific benchmark of me counting) so it could maybe be more aggressive. Making it a very low number wouldn't effect me at all because I used starred pipelines for the ones I care about. Could be a problem for other users though.

This is good enough for me though so I'm happy to have this closed. Thanks again :)

**Comment by ticky** [comment]
It’s a balance I’m mindful of, as we have some customers with 600+ pipelines who want quick access, and some with fewer pipelines for whom it doesn’t matter as much. Hopefully in the near future we’ll have a better balance for both.

Glad it’s an improvement, though! 😃
