### ISSUE TITLE
UI makes pending steps look like they failed

### ISSUE THREAD

**Issue by mdub** [buildkite/feedback#254]
In this pipeline run, the red background suggests that the last two steps ("OK to Release" and "Release") ran, and failed:

<img width="461" alt="screen shot 2017-05-06 at 2 21 28 pm" src="https://cloud.githubusercontent.com/assets/610/25769849/cfefea96-3267-11e7-8a6e-8100844afa70.png">

In fact, they didn't run at all, due to the failing "Test" step.  I suspect a CSS bug. Didn't steps that hadn't yet executed used to be grey, or yellow, or something?

**Comment by ticky** [comment]
Hi @mdub, thanks for the feedback! This duplicates #236, so I’m going to close this ticket.
