### ISSUE TITLE
[username]@users.noreply.github.com email addresses cannot be "owned" in buildkite

### ISSUE THREAD

**Issue by afirth** [buildkite/feedback#258]
## Summary
Github recently rolled out more support for private email addresses of the form [github-username]@users.noreply.github.com. However, associating your buildkite account with github doesn't add this address, and it can't be added manually as it's a blackhole that doesn't verify. As a result, builds triggered by these commits are unowned.

## See also 

[#122](https://github.com/buildkite/feedback/issues/122#issuecomment-132299825)  "Easiest way is for them to connect their GitHub account to Buildkite (or manually add their git email)."

## Expected behavior
Commits from [username]@users.noreply.github.com show up as "mine" in buildkite after my github account is attached

## Observed behavior
Commits show up without an owner. Attempting to add the email manually as prompted sends a verification (which goes to a black hole as expected)

## Steps to reproduce
1. [Enable github private emails](https://github.com/settings/emails)
2. Commit to a branch which triggers a build using the private email as your author (for example through the github web interface)
3. Observe build author unknown

## Suggestions
A simple workaround may be to add [github-username]@users.noreply.github.com for accounts associated with a github account.

**Comment by afirth** [comment]
I can't reproduce this anymore since I've associated my github acct, although it still doesn't show up as "my" email or associate earlier builds. Closing

**Comment by ticky** [comment]
HI @afirth,

We’ve recently rolled out a change which will correctly associate builds with people who’ve associated their GitHub account which has a private email address, but it doesn’t yet work retroactively. We hope to have a fix for that out very soon!

If you’ve got someone with that privacy setting on and their account connected, chances are they connected prior to the patch, so if you get them to remove and re-link their GitHub account with their Buildkite account, it should all work smoothly for them.

Apologies for the complexity!

**Comment by poeske887** [comment]
posn1255@user.noreply.github.com

**Comment by CharlieccGuo** [comment]
44990977+CharlieccGuo@users.noreply.github.com

**Comment by kyledecot** [comment]
We've just started noticing this issue–has there been a regression @ticky?

**Comment by chrisnankervis** [comment]
We experienced this recently but it seemed to be happening intermittently; only one in every few builds would fail due to the user's unverified private email address.

We contacted Buildkite's support team and they recommended that the user connect their Github account to their Buildkite account via the [Connected Apps](https://buildkite.com/user/connected-apps) section to avoid this issue 👍

**Comment by salahfaf** [comment]
Aim github thank you suerskraib

**Comment by zhtw1234** [comment]
本帳號本名周訓毅1976-04-28，目前無業在家。以前是復康巴士司機，目前是第2次婚姻，前妻生2子

**Comment by zhtw1234** [comment]
本人周訓毅，喜歡打老婆，騙網路上笨女人

**Comment by X3bufe** [comment]
62649613+X3bufe@users.noreply.github.com

**Comment by 39r762193i** [comment]
> ## Summary
> Github recently rolled out more support for private email addresses of the form [github-username]@users.noreply.github.com. However, associating your buildkite account with github doesn't add this address, and it can't be added manually as it's a blackhole that doesn't verify. As a result, builds triggered by these commits are unowned.
> 
> ## See also
> [#122](https://github.com/buildkite/feedback/issues/122#issuecomment-132299825) "Easiest way is for them to connect their GitHub account to Buildkite (or manually add their git email)."
> 
> ## Expected behavior
> Commits from [username]@users.noreply.github.com show up as "mine" in buildkite after my github account is attached
> 
> ## Observed behavior
> Commits show up without an owner. Attempting to add the email manually as prompted sends a verification (which goes to a black hole as expected)
> 
> ## Steps to reproduce
> 1. [Enable github private emails](https://github.com/settings/emails)
> 2. Commit to a branch which triggers a build using the private email as your author (for example through the github web interface)
> 3. Observe build author unknown
> 
> ## Suggestions
> A simple workaround may be to add [github-username]@users.noreply.github.com for accounts associated with a github account.

**Comment by KimberlySama** [comment]
55718757+KimberlySama@users.noreply.github.com

**Comment by natmaxwell83** [comment]
#my messages won't show what do I need to do

**Comment by ticky** [comment]
Please contact support@buildkite.com with your GitHub account name and email address for us to fix this up for you.
