### ISSUE TITLE
Per-section timing information on output

### ISSUE THREAD

**Issue by mipearson** [buildkite/feedback#26]
Buildbox allows me to group sections of the output and then only view that section. What would be really useful is if we could get timing information on each section.

eg:

```
> bundle install (30s)
> rspec (2m 3s)
> cucumber (1m)
```

**Comment by keithpitt** [comment]
We've got this figured out...coming soon to a build log near you!

**Comment by keithpitt** [comment]
Oh, we totally shipped this as well, so if you update to the latest beta agent, you should get this feature :)
