### ISSUE TITLE
feature requests for pipeline

### ISSUE THREAD

**Issue by ozbillwang** [buildkite/feedback#261]
Put all requests about pipeline together, if you are already working on some of them , please share the ticket numbers, I can update. 

- [x] search pipeline

- [ ] group pipelines

I am assigned to a team under an organization. A lot of pipelines are created in my team, I hope to create sub-groups, move the pipelines in different sub-groups, so we can arrange these pipelines easily. 

I guess to implement this will be harder than search feature. If you can make the search works, I am fine without group feature.

- [ ] Slack notification in each pipeline.

I have no permission to access organization setting. So need feature that I can set slack notification in the pipeline setting.  It will be better if I can put slack setting in `pipeline.yml` file directly.

That's not only for slack notification, same for other features if they are useful, but in an organization setting only. 

- [ ] default agent queue

Currently, I need to add below lines to each step in  `pipeline.yml`

    agents:
      queue: 'agent-1

Can we have a feature to set default agent for each team? So if the pipeline under this team, will assign to default agent. 

Or if can, set agents queue to top level in `pipeline.yml`
 
- [ ] schedule job in pipeline can be temporarily disabled 

So I needn't to delete and add it back if I want to test something. 

- [ ] Have H (for "hash") feature in schedule job. 

`H * * * * `

>To allow periodically scheduled tasks to produce even load on the system, the symbol H (for “hash”) should be used wherever possible. For example, using 0 0 * * * for a dozen daily jobs will cause a large spike at midnight. In contrast, using H H * * * would still execute each job once a day, but not all at the same time, better using limited resources.

**Comment by lox** [comment]
Relevant tickets are:

* Group pipelines https://github.com/buildkite/feedback/issues/129 
* Top-level agent targeting https://github.com/buildkite/feedback/issues/173

**Comment by lox** [comment]
I'm going to close this one out, feel free to break those two out into different issues if you still need them @ozbillwang.
