### ISSUE TITLE
Could we show Agent Pass/Fail History

### ISSUE THREAD

**Issue by bencmorrison** [buildkite/feedback#264]
It would be great to somehow see agent pass and fail rates for a pipeline.
Right now we are running into an issue where we are getting occasional fails from our agents. It is rather hard to track if it is a single agent that is failing the builds or we have a larger issue. Currently, we are able to track down an issue by going through the many builds that day. We have found in the past a single agent was failing builds but that require a lot of time to track down what agent was causing us issue. An ability to see a summary would greatly help with tracking down issues over time.

**Comment by ticky** [comment]
Hey @bencmorrison!

I’ve just added ten jobs’ worth of history to the agents page (buildkite/frontend#352). I suspect this doesn’t completely cover your use case as I think you want longer-term stats, but I hope this helps in the interim! 😄

**Comment by bencmorrison** [comment]
Awesome! It will certainly be helpful!

**Comment by mdub** [comment]
Lovin' it already!
