### ISSUE TITLE
Pipeline search

### ISSUE THREAD

**Issue by benschwarz** [buildkite/feedback#265]
Hey! 

Great to see the new pipelines page search - I understand others have a lot more pipelines than I do, and pagination comes into play… I'm sure that is why the search is server-side rather than client side. 

However, that means that any search that I conduct has a 500ms delay and a kind of jarring user experience. It'd be amazing if *both* the DOM was searched, while making a server side request.

Apart from that: If search has focus, it'd be amazing to hit the down arrow on my keyboard a couple of times and have it highlight pipelines… the <enter> key could navigate me to it.

**Comment by ticky** [comment]
Hey Ben, you’re spot on about why we did it server side as a first pass. Previously we’ve built searches which do a hybrid local/remote search, too, and I’d love to get this doing that!
