### ISSUE TITLE
Full functions of Cloudformation teamplate for windows buildkite agents

### ISSUE THREAD

**Issue by ozbillwang** [buildkite/feedback#266]
With repo `https://github.com/buildkite/elastic-ci-stack-for-aws`, I can start up buildkite agents easily, but looks these are linux agents. 

Could I have official Cloudformation template to start up windows buildkite agents? We have a team who need to migrate CI/CD pipelines from `teamcity` (windows agents) to Buildkite, a lot of Powershell I need to deal with, so re-write them by linux shell script is not a choice.

The linux template is at https://s3.amazonaws.com/buildkite-aws-stack/aws-stack.json

I need a similar tempalte for windows agents

**Comment by lox** [comment]
Closing this in favour of https://github.com/buildkite/elastic-ci-stack-for-aws/issues/286
