### ISSUE TITLE
Pipeline admins cannot grant other (visible) teams access to their pipelines

### ISSUE THREAD

**Issue by mdub** [buildkite/feedback#267]
It appears that #166 has re-appeared.

We tested as follows:

- ensure User D (@tigris) is not a site "Administrator"
- ensure User D has "Full Access" to "Pipeline X"
- ensure User D is not an admin for "Team B"
- ensure "Team B" is "Visible"
- get User D to grant "Read-Only" access on "Pipeline X" to "Team B"

This failed, because User D could not see "Team B" in drop-down list on the Pipeline Settings page.

**Comment by mdub** [comment]
In further testing, we added User D to "Team B" as a "Team Member" ... at which point they could see the team, and grant access.  But, we want to people to be able grant access to teams they are _not_ members of.

**Comment by keithpitt** [comment]
I've just confirmed we've regressed. Ive tracked it down to some bugs in our UI not showing the relevant records. I'll have it fixed by COB today! Sorry about the regression @mdub - thanks for letting us know!

**Comment by keithpitt** [comment]
@mdub we've just pushed out some fixes which should address this issue, and bring back the behaviour. Can you confirm for me?

**Comment by mdub** [comment]
Confirmed! Thanks for the quick fix, @keithpitt.
