### ISSUE TITLE
See how long a step has been waiting

### ISSUE THREAD

**Issue by missyjcat** [buildkite/feedback#274]
It would be great to see how long a step has been waiting.

I see the total time a build has been running, but see that the first couple steps took <1 min each and the third step has been waiting awhile. I have to do mental math to figure out how long its been waiting. 

The step could show a count of long it is waiting for an agent and the final stats will show how long each step had to wait for an agent.

![image](https://user-images.githubusercontent.com/1158471/29891971-cd9c0494-8d81-11e7-92cf-569f1bbdfbef.png)
![image](https://user-images.githubusercontent.com/1158471/29891974-d167cae0-8d81-11e7-8c75-d7f117a95838.png)

**Comment by toolmantim** [comment]
Thanks for the feedback! This is something people have wanted for a while. I like the idea of putting the timing on the "Waiting for agent"… just need to figure out where to put it for the total wait time as well.

**Comment by seanabraham** [comment]
Yes, I'd also like this! There is a reasonable proxy for this information if you look at the agent tab in a given step (it says when the job was scheduled, then assigned to agent, etc.) but if there was a more clear indicator of this on the top level page for the build (or some visual indicator perhaps) that would be great!

**Comment by keithpitt** [comment]
@missyjcat thanks for the great suggestion! (we should have closed this earlier sorry) but we do show how long a step has been waiting for an agent now! 🚀 

<img width="406" alt="image" src="https://user-images.githubusercontent.com/25882/49000050-6910df00-f193-11e8-9afa-032b0387bba4.png">
