### ISSUE TITLE
Get the Base Branch of a PR 

### ISSUE THREAD

**Issue by cycomachead** [buildkite/feedback#277]
Most of the time, we merge PRs into master, but it would be nice for a couple tools if we could get an  environment variable that has the branch name of what a PR will be merged into. 

Is there any way to do this today? I read the docs on environment variables and didn't see anything.

Thanks!

**Comment by toolmantim** [comment]
Hey, thanks for submitting this. Weren't working on this now, and it's not far away. I'll keep you posted when it's live.

**Comment by cycomachead** [comment]
Thanks! That's great to hear.

**Comment by mfeckie** [comment]
How's this going folks? Very keen to use this as target merge branch targetting is what we use to determine where we want a successful build to be deployed

**Comment by toolmantim** [comment]
Hey, it actually just went live this morning 🎉 You can find `BUILDKITE_PULL_REQUEST_BASE_BRANCH` in the [list of environment variables](https://buildkite.com/docs/builds/environment-variables) and in any pull request job’s "Environment" tab.

**Comment by cycomachead** [comment]
Awesome, thanks so much!

**Comment by mfeckie** [comment]
❤️ 💟 💛 💜 💚 ❤️ 💙
