### ISSUE TITLE
Allow more than one Build Pipeline per project 

### ISSUE THREAD

**Issue by danthorpe** [buildkite/feedback#28]
Hi Keith, First off, love Buildbox - been a relatively early supporter and advocate.

Something which I'm wondering how to do, and suspect that it's not possible at the moment, is to have more than one build pipeline in the same project.

So, say for example, I just want to run unit tests on feature & development branches. But I want to do more complex staging, and/or automated testing, and/or deployment to beta tests, and/or archiving on integration or release branches. While, I guess in theory this might be possible to configure all in the same pipeline, I think it would also be must easier to digest and maintain if it were possible to define pipelines based on unique branch sets.

So, I could do this with multiple projects all pointing at the same repo - but, that's a bit lame.

For what its worth, I use Buildbox as CI for iOS projects. Native applications have slightly different usage, and therefore CI requirements, from web projects. Mostly that continuous deployment is not needed, although we still want automated deployment :)

Would love to hear your thoughts on this,

Cheers,
Dan

**Comment by toolmantim** [comment]
I think we can say this is not an issue now, since we've renamed projects to pipelines?
