### ISSUE TITLE
Only trigger builds on tagged commits

### ISSUE THREAD

**Issue by cwalo** [buildkite/feedback#299]
We'd like to only trigger builds by pushing a tagged commit. Currently, it looks like our only options are to use `[skip ci]` for every other commit or just use the buildkite API with some other github webhook. Do I have that right?

-Corey

**Comment by ticky** [comment]
You can achieve this by setting a branch filter with an extremely unlikely branch name (like, say, `please/dont/build/anything`), which will mean that we build nothing based on push. Then under your repository provider settings (GitHub, GitLab, etc.) configuring it to only build tags, so you’d end up with a configuration like this:

<img width="729" alt="screen shot 2017-11-28 at 11 26 24 am" src="https://user-images.githubusercontent.com/282113/33296324-0319646a-d42f-11e7-92a1-dc7c63c1a0f6.png">

The reason this works is that builds triggered from Pull Requests or Tags ignore the global branch filter and operate with their own configuration!

I hope we can make this sort of setup simpler in the future. 😄

**Comment by cwalo** [comment]
@ticky Ah, a little hacky, but good enough for now! Thanks!

**Comment by liyanone1990** [comment]
Hi, may I know how to configure building on pushed tag on gitlab repo? There is no gitlab settings section on buildkite pipeline settings. After I enable the webhook with gitlab and select Tag push events trigger, no matter I create tag on gitlab or git push tag remotely, it actually nothing happened on buildkite.

**Comment by PJHaynes304** [comment]
"The reason this works is that builds triggered from Pull Requests or Tags ignore the global branch filter and operate with their own configuration!"

@ticky is this still the case? After setting a branch filter and configuring to build tags as suggested no builds are triggered when I push a tag up...

The reason I ask is that the Build pull requests configuration has a comment saying pipeline-level branch filtering is ignored but the Build tags configuration does not.
![screen shot 2018-07-23 at 15 32 20](https://user-images.githubusercontent.com/33064190/44456389-44d3be00-a5f8-11e8-817c-c3047b58b3ab.png)

**Comment by oj22** [comment]
@ticky - I am unable to find the setting in Github. which you have mentioned.can you please help to find out

**Comment by keithpitt** [comment]
@oj22 👋 ah sorry, the setting is in Buildkite - not GitHub.

In Buildkite, go to your Pipeline Settings:

![image](https://user-images.githubusercontent.com/25882/69504748-815f3980-0f60-11ea-829a-26d710e80ce4.png)

Then the GitHub Settings:

![image](https://user-images.githubusercontent.com/25882/69504758-8fad5580-0f60-11ea-9faf-8c56e2db2585.png)

You'll see the option in here:

![image](https://user-images.githubusercontent.com/25882/69504776-ace22400-0f60-11ea-80d1-bceb6409932c.png)

**Comment by mskonovalov** [comment]
It doesn't seem to work anymore (at least in my setup).
If on GH webhook you choose to send only `Branch or tag creation` event it doesn't trigger the build.
So if you add event `Pushes` in GH webhook it starts. But it treats tag same way as branch, so specifically wrong branch name doesn't work anymore.
So you can solve this by naming tags like `release-x.y.z` and setting branch filter pattern to `release-*` or something similar
