### ISSUE TITLE
Collapse "---" sections in running build logs

### ISSUE THREAD

**Issue by sj26** [buildkite/feedback#3]
We're running a bunch of prep tasks like creating databases, clearing out search indexes, etc., which are boring and I don't want to see. They each have a "---" header. My main spec/cuke outputs have a "+++" header.

I'd like the "---" sections to be hidden by default in running build logs, or perhaps shown until they complete then hidden.

**Comment by keithpitt** [comment]
The `---` logs are now hidden by default.
