### ISSUE TITLE
404 when trying to convert new/empty steps to YML

### ISSUE THREAD

**Issue by mallyvai** [buildkite/feedback#300]
Bug report:  When you:
1) Create a new buildkite pipeline
2) Setup the webhook
3) There are no steps yet defined (including no default ones - the steps area is empty)
4) You hit the ‘convert to YML button’
5) You get taken to a 404 page that says the organization / pipeline wasn’t found

**Comment by sj26** [comment]
Hi @mallyvai — I think we've shipped a fix here and it should be available shortly. Thanks for the report!

**Comment by Artic2017** [comment]
Helloy
