### ISSUE TITLE
triggering build that is "skipped" stalls pipeline

### ISSUE THREAD

**Issue by skunca** [buildkite/feedback#310]
In a pipeline that triggers another pipeline that has the "Skip Intermediate Builds" option enabled, if the triggered build is skipped then the original pipeline just waits on the trigger step forever. 

Is there any way to continue the original pipeline in such a case? Using **async** on the trigger doesn't work since we want to bail when triggered builds fail and **async** trigger steps never fail.

**Comment by keithpitt** [comment]
@skunca I rolled out a fix for this today! 🚀 The triggering step will now show as "skipped" in the UI and won't stall the pipeline.

Sorry it took a while to get out!
