### ISSUE TITLE
Allow [skip ci] tag to be upper case

### ISSUE THREAD

**Issue by nullobject** [buildkite/feedback#312]
It seems that the `[skip ci]` tag must be specified in lower case. It would be better if it was case-insensitive so that users can match their preferred tagging style (we use upper case for example).

**Comment by keithpitt** [comment]
A fix for this is going live now :) In about 10 minutes, both `[skip ci]` and [SKiP cI]` will #justwork!

**Comment by nullobject** [comment]
Ace, thanks very much 🎉
