### ISSUE TITLE
Add Enable/Disable flag for schedules

### ISSUE THREAD

**Issue by jnewbigin** [buildkite/feedback#315]
If you have a scheduled build  (eg. a Daily Build) but you don't want to run it for a few days, it would be ideal to set it to _disabled_ so when you are ready to re-enable it, you don't need to remember all the settings (as you would have to do if you delete and re-create the schedule)

**Comment by felixfbecker** [comment]
I believe this is supported

![image](https://user-images.githubusercontent.com/10532611/41633224-a12d5dce-73f2-11e8-83ba-9eccc55446dd.png)

![image](https://user-images.githubusercontent.com/10532611/41633233-af3d7980-73f2-11e8-940b-0374f02ca72f.png)

**Comment by jnewbigin** [comment]
Looks good.

**Comment by toolmantim** [comment]
Oh yep, this is live and shipped! 🎉 Thanks @felixfbecker.

Sorry we didn't update this issue earlier @jnewbigin!
