### ISSUE TITLE
Let me switch an agent off temporarily

### ISSUE THREAD

**Issue by mipearson** [buildkite/feedback#32]
Right now it looks like I have to go to each individual build step to switch agents off.

One of our build boxes ran out of disk because stale filehandles and docker and computers. Builds would auto-fail. Being able to switch off that agent temporarily until we could fix it would have been useful.

**Comment by keithpitt** [comment]
If you are running the latest agents, you can now remotely turn agents off! :)

**Comment by sj26** [comment]
Look at you. What a machine!
