### ISSUE TITLE
Gradle log level parameters ignored

### ISSUE THREAD

**Issue by vyphan** [buildkite/feedback#321]
In one of my builds, I have a command step that executes a shell script, inside of which I run a Gradle task. I want to reduce the log output from this Gradle task. I've tried passing in both "-Dorg.gradle.logging.level=quiet" and "-q" and they both reduce the output locally, but neither one works in the Buildkite step.

Agent version is v3.0-beta.27 and I'm using the docker-compose#v1.5.0 plugin.

**Comment by keithpitt** [comment]
@vyphan 👋 I just saw you shoot an email to support as well, I might close this one here and take it to email so I can get some specifics off you :)

**Comment by itsmeduncan** [comment]
@keithpitt If there is information for the rest of us, please post here!
