### ISSUE TITLE
Error message duplicated when inviting a user that is already a member

### ISSUE THREAD

**Issue by philwo** [buildkite/feedback#325]
When you try to send an invite to an e-mail address that is already registered and a member of your organization, the error message is shown twice:

<img width="716" alt="screen shot 2018-03-15 at 08 12 24" src="https://user-images.githubusercontent.com/504652/37448965-c91eef20-2828-11e8-8d99-3c17d59f0346.png">

**Comment by ticky** [comment]
Hi @philwo, thanks for the report! I think I’ve figured out where this duplication is coming from, so I’ll see if we can get that fixed pretty soon. :)

**Comment by philwo** [comment]
Thanks for the quick fix, @ticky! Buildkite and your team are the best. 😊
