### ISSUE TITLE
Don't combine time for dependent pipelines into parent pipeline's dash

### ISSUE THREAD

**Issue by rmtobin** [buildkite/feedback#326]
We have a build pipeline that runs tests and other things on all our repo's branches. When it is run on the master branch, it does a merge then triggers a separate deploy pipeline. We want to show the master branch as the default branch in the dashboard view since that is our primary "known good" branch. However, since it triggers the deploy pipeline, the timing on the dashboard is a combination of the timing for the build and deploy pipelines combined.

As an example, the build pipeline takes 4 mins and the deploy pipeline takes 8, the time for the build pipeline will show 12 mins. This is unfortunate because the build pipeline dash is no longer representative of non-master runs of the build pipeline and is less useful for determining per-pipeline trends. It also is not obvious that the timing for the build pipeline is a combination of it plus dependent pipelines, and requires you to know the relationship between the pipelines and then do math to determine actual timings.

I'd propose that the timing on the dashboard show only the timing for the steps executed as a part of that pipeline and not include timing for dependent pipelines.

**Comment by sj26** [comment]
Hi @rmtobin! In your [trigger step](https://buildkite.com/docs/pipelines/trigger-step), are you setting `async: false`? If you remove this then your master build will finish while your deploy build continues, and will not include the timing. This is how we build and deploy Buildkite itself!

**Comment by rmtobin** [comment]
@sj26 Ah, I had it unset and that was not the behavior I was expecting coming from Jenkins (which defaults to async). With this and concurrency groups it looks like that will solve the issue. Thanks!

**Comment by sj26** [comment]
Glad to hear you got it working @rmtobin, sorry it's not quite as expected!
