### ISSUE TITLE
Add option for enqueued automatic retries to take precedence over later builds

### ISSUE THREAD

**Issue by shamanskyh** [buildkite/feedback#328]
Hey Buildkite! I love the new automatic retry feature. One small feature request, though:
When a step in a pipeline fails, the new step often takes a while to re-run since it has to re-aquire an agent and our pool of agents is, sadly, not very large.

It seems like the behavior is for steps to be run in the order that they were enqueued/uploaded, but it'd be ideal if one of the two options were possible:
- Automatic retries stay with the same agent on which the job failed so that it doesn't have to re-acquire an agent
- Prioritize retried steps in agent acquisition by ordering them by the time of the _original_ step (the failure) and not the newly enqueued step.

Let me know if this doesn't make sense and I'd be happy to explain further. And thanks again for the new automatic retries!

**Comment by ticky** [comment]
I believe this has been fixed. Thanks for the feedback! :)

**Comment by shamanskyh** [comment]
Thanks @ticky!
