### ISSUE TITLE
Feature request: Timestamps in build log output

### ISSUE THREAD

**Issue by gh2k** [buildkite/feedback#330]
I'd like to know how long a particular part of my build took. It would be helpful to have a timestamp prepended to every line in the log output (optionally?) so I can see this.

**Comment by BRMatt** [comment]
It might be worth piping your logs through the `ts` command: https://unix.stackexchange.com/a/26797/6459

**Comment by KevinGrandon** [comment]
I believe there is a buildkite agent command for this, `timestamp-lines`, that you can turn on: https://buildkite.com/docs/agent/v2/configuration

It would be nice to hvae this option to turn this on in the UI as well though.

**Comment by gh2k** [comment]
Thanks - I couldn't find a straightforward way to do that on my Windows agents so it would still be convenient to have it available as an option somewhere. :)

**Comment by gh2k** [comment]
@kevingrandon Oh, that works for me. I hadn't seen it in the config file, didn't look there.
