### ISSUE TITLE
"My Builds" shows "1 Running" build, but no build is running.

### ISSUE THREAD

**Issue by philwo** [buildkite/feedback#341]
Clicking on the "1 Running" build shows a page saying: "You have no running builds"

Did something get out of sync?

<img width="744" alt="screen shot 2018-04-12 at 06 34 56" src="https://user-images.githubusercontent.com/504652/38656588-ce91922e-3e1b-11e8-94e7-022b6d285f97.png">

**Comment by gtirloni** [comment]
It seems to be working here: 
![screenshot from 2018-04-12 17-27-51](https://user-images.githubusercontent.com/5902830/38702406-f3f16778-3e76-11e8-98c4-55d123acdeb5.png)

Could it be that you have a build that is blocked?

**Comment by philwo** [comment]
It's possible that there's a build somewhere that is blocked, but I have no way of finding it.

I don't think this is working as intended - if you click on a button that says "1 Running" and then you get a page that says "You have no running builds" (and it still shows the "1 Running" button in the top, so it didn't finish in the meantime), then there's a bug somewhere. :)

**Comment by baank** [comment]
I have experienced this as well and it's incredibly annoying.

The solution is simple:

41 builds | 0 running | 1 blocked | 0 scheduled.

**Comment by philwo** [comment]
I don’t understand what you mean with “The solution is simple: 41 builds | 0 running | 1 blocked | 0 scheduled.”

Also, you seem to have a different issue (1 blocked build - can you see it an unblock it?)

In my case, I just send a mail to the support and they fixed it the same day. Buildkite being awesome as usual. :)
