### ISSUE TITLE
GET /builds doesn't return all retried jobs

### ISSUE THREAD

**Issue by gtirloni** [buildkite/feedback#346]
This URL will return a list of all jobs in the build, including retried jobs (stored in `store` variable) :

```
https://buildkite.com/fluid-project/fluid-infusion/builds/191
```

This URL will only return one instance of each job, which doesn't include multiple retries:

```
https://api.buildkite.com/v2/organizations/fluid-project/pipelines/fluid-infusion/builds/191
```

**Comment by sj26** [comment]
Hi @gtirloni — sorry about that, we didn't want to change the API too much when we first released retries. I've just added a parameter so you can ask these endpoints to include retried jobs:

```
https://api.buildkite.com/v2/organizations/fluid-project/pipelines/fluid-infusion/builds/191?include_retried_jobs=true
```

Jobs should have two new properties — `retried: true/false` and `retried_in_job_id: null/"UUID"` — which indicates whether that job has been retried, and the id of the job it is retried in. The referenced job should have a `retries_count` one higher than the retried job. We'll update the docs soon.

**Comment by gtirloni** [comment]
@sj26 that was super fast, thanks a lot!
