### ISSUE TITLE
Update base docker image to alpine 3.7

### ISSUE THREAD

**Issue by nicksnyder** [buildkite/feedback#348]
[Alpine 3.7](https://alpinelinux.org/posts/Alpine-3.7.0-released.html) was released 2017-11-30. It would be nice to have that as a base image. 3.6 has a lot of old packages.

This would be unnecessary if https://github.com/buildkite/feedback/issues/144 was fixed instead (but I imagine updating the base image is easier).

**Comment by sj26** [comment]
Sounds like a nice idea! I'd love to build a package, too, but our images could use an update.

**Comment by sj26** [comment]
Done!

**Comment by nicksnyder** [comment]
Thanks! When do you think a release will get tagged?

**Comment by sj26** [comment]
@nicksnyder buildkite/agent:3.1.1 should be built on alpine:3.7.
