### ISSUE TITLE
better documention for timestamp-lines	

### ISSUE THREAD

**Issue by aaronorosen** [buildkite/feedback#349]
I needed to add: timestamp-lines=true to: buildkite-agent.cfg in order to get the timestamps to show up in the logs. 

- It would be nice if this option was added to buildkite-agent.cfg but commented out with a description above like several of the other config options.

-  It would be even better if this could be dynamically enabled and disabled by setting the BUILDKITE_TIMESTAMP_LINES env variable. This way users don't need to deal with updating the cfg file and restarting the agent.  Setting that env variable does not seem to work without first editing the buildkite-agent.cfg.

**Comment by toolmantim** [comment]
Thanks for the feedback! That sounds very reasonable. Any chance you could open this issue on https://github.com/buildkite/agent?

**Comment by aaronorosen** [comment]
Done.

**Comment by toolmantim** [comment]
Thanks, I've copied over the issue description there as well.
