### ISSUE TITLE
Feature: Build support for Docker Buildkite Plugin

### ISSUE THREAD

**Issue by baank** [buildkite/feedback#358]
Would be great if there was a Docker Buildkite Plugin that was largely identical to the Docker Compose Buildkite Plugin only it worked with single image Dockerfiles. 

In particular the ability to build images.

**Comment by toolmantim** [comment]
Would you mind opening an issue up on https://github.com/buildkite-plugins/docker-buildkite-plugin instead? Thank you! 🙏🏼
