### ISSUE TITLE
I'd love to see build time trends

### ISSUE THREAD

**Issue by macosgrove** [buildkite/feedback#37]
My build yesterday took two minutes longer than the previous build. I wanted to know whether that was because I'd introduced a performance issue, or if was within the normal range over time. So I'd love to see a time-series graph of build times like you get with Jenkins or Hudson.

**Comment by keithpitt** [comment]
We have trends on the Dashboard now! 🕐 Sorry it took so long!

https://building.buildkite.com/new-in-buildkite-pipeline-metrics-b5e7bf187272#.eorvsq7yz

<img width="967" alt="screen shot 2016-11-03 at 5 45 55 pm" src="https://cloud.githubusercontent.com/assets/25882/19961461/b3862394-a1ed-11e6-900b-935442143ef8.png">
