### ISSUE TITLE
Expose BUILDKITE_PARENT_BUILD_ID

### ISSUE THREAD

**Issue by joscha** [buildkite/feedback#387]
Currently there is no easy way to get the triggering job of a build unless passing

```yaml
env:
  PARENT_BUILD_ID: ${BUILDKITE_BUILD_ID}
```

it would be great to get a generic `BUILDKITE_PARENT_BUILD_ID` for this.

**Comment by toolmantim** [comment]
Good suggestion! I'm just wondering if the build UUID is going to be enough? Because the job/build that triggered it could be from any pipeline.

**Comment by joscha** [comment]
O, I was under the impression that the UUID is all I need to get artifacts from that pipeline for example. I guess more information wouldn't be wrong.

**Comment by toolmantim** [comment]
Actually I've just done some digging, and I think you're right, all you'll need is the build UUID.

**Comment by toolmantim** [comment]
`BUILDKITE_TRIGGERED_FROM_BUILD_ID` is now available 🎉 The docs will be updated shortly too.

**Comment by joscha** [comment]
Awesome, thank you!

**Comment by lox** [comment]
I'm going to close this one!
