### ISSUE TITLE
Let *.ryver.com validate as a Slack URL

### ISSUE THREAD

**Issue by ineffyble** [buildkite/feedback#388]
Our team has recently moved from Slack to Ryver for our group messaging.

Ryver offers Slack-compatible webhooks - meaning that a webhook in Slack message format will be converted to a Ryver message automatically, with no manual effort required.

However, when I tried to add a new Slack integration with our *.ryver.com URL, it was automatically disabled by Buildkite as an "invalid Slack URL". Any chance you can add Ryver's domain to the whitelist of Slack-like domains?

**Comment by toolmantim** [comment]
Thanks for the context and posting this.

We’ve added *.ryver.com as a valid slack webhook URL, so you can go and do that now 🎉

Let us know if there’s any problems with it (probably best on support)

**Comment by ineffyble** [comment]
It works! Thank you.

**Comment by toolmantim** [comment]
You’re welcome 😊
