### ISSUE TITLE
REST API only allows setting team UUIDs on pipeline create

### ISSUE THREAD

**Issue by haines** [buildkite/feedback#400]
The `team_uuids` field isn't returned in GET requests (or in the response to POST or PATCH), and is ignored in PATCH requests.

**Comment by petemounce** [comment]
@ashleydavies spotted this too, and worked around it by using the GraphQL API.

**Comment by keithpitt** [comment]
👋 hey @haines - sorry for the late reply to this one!

Ah yeah - so as you noticed we do support the `team_uuids` field in pipeline create, however that's mostly there for compatibility reasons (if you turned on teams, and had a bunch of scripts that generated pipelines - things would break for your users pretty quickly when the team permission system kicks in)

We don't have any plans to expand on team management in the REST API at the moment, but you can do everything team related in the GraphQL API https://buildkite.com/docs/apis/graphql-api

If you need a hand with any queries - we're happy to help (support@buildkite.com or hop over to https://forum.buildkite.community/c/help)
