### ISSUE TITLE
Better (any?) CSS styles for tables in annotations

### ISSUE THREAD

**Issue by clarkdave** [buildkite/feedback#402]
Hey folks!

At the moment, tables in an annotation look pretty bad:

![image](https://user-images.githubusercontent.com/729557/41128154-24f198a2-6aa5-11e8-822c-47747c1432a8.png)

Even some basic styling on table elements here would go a long way! We'd really like to use tables to output various statistics but the lack of styling is a bit of a blocker. Inline styles seem to be stripped too so that's not an option either.

---

HTML used for the above:

```html
<table>
  <thead>
    <tr>
      <th></th>
      <th>parsed size</th>
      <th>gzip size</th>
      <th>link</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>main.js</td>
      <td>558.1 KB</td>
      <td>154.65 KB</td>
      <td>
        <a href="artifact://build/stats.html">
          build/stats.html
        </a>
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by keithpitt** [comment]
@clarkdave we can do this!

Do you have an idea of what you'd want it to look like? If you pasted some CSS suggestions I should be able to copy/paste into the app :)

**Comment by ticky** [comment]
Hi @clarkdave! We’re shipping a change now which adds styles for tables. We’ve derived these from GitHub’s [Primer](https://github.com/primer/primer) project, so they’ll match up with what GitHub use pretty well 😄
