### ISSUE TITLE
Manage scheduled builds over REST API

### ISSUE THREAD

**Issue by felixfbecker** [buildkite/feedback#406]
When doing automation through shell scripts, the REST API is simpler to work with. It would be nice if it supported edits of scheduled builds (e.g. toggling `enabled`).

**Comment by keithpitt** [comment]
👋 hey @felixfbecker - thanks for the suggestion!

We don't have any current plans to add any new top level resources to the REST API I'm afraid. You can our GraphQL API however to manage scheduled builds (using the `pipelineScheduleCreate` mutation) https://buildkite.com/docs/apis/graphql-api

If you need a hand with any queries - we're happy to help (support@buildkite.com or hop over to https://forum.buildkite.community/c/help)
