### ISSUE TITLE
Support markdown tables in annotations

### ISSUE THREAD

**Issue by bjeanes** [buildkite/feedback#408]
It'd be great to be able to express tabular output in annotations from markdown (which is easy to generate from scripts):

![2018-06-21 at 7 49 pm](https://user-images.githubusercontent.com/2560/41711786-3d74e3c4-758c-11e8-9030-cff020267414.png)

Not urgent, as I can workaround by generating HTML:

![2018-06-21 at 8 12 pm](https://user-images.githubusercontent.com/2560/41713088-8b928540-758f-11e8-8bb4-67cba39230bf.png)

**Comment by ticky** [comment]
@bjeanes we’ve updated our Markdown renderer to handle this syntax!

You should be able to use most GitHub Flavored Markdown features now, aside from syntax highlighting, task lists, user mentions, and automatic links for references to issues, pull requests or commits.

**Comment by bjeanes** [comment]
@ticky yay that was fast. Thank you
