### ISSUE TITLE
Queue-specific agent tokens

### ISSUE THREAD

**Issue by pauldraper** [buildkite/feedback#421]
As far as I can tell, it's often the case that committers directly or indirectly have access to the machine, build agent, and associated credentials.

I could secure build machines via different queues. However, there is no per-queue security.

I suggest allowing admins to assign queues to different agent tokens. This would provide a simple, robust mechanism for build security.

**Comment by toolmantim** [comment]
Thanks for the feedback. We're working on just this, and you're spot on with the problem there. You'll definitely know when it's ready. I'll keep this open here though for reference.

**Comment by pauldraper** [comment]
Excellent! I look forward to it.

**Comment by pauldraper** [comment]
Ah, that's actually a pretty good workaround. Thanks!

**Comment by yeungda-rea** [comment]
As a Buildkite organisation admin, I'm interested in having the ability to scope an agent token to a queue.

**Comment by lox** [comment]
We have big plans on this front, moving discussion over to https://forum.buildkite.community/t/restricting-access-to-agents/200.
