### ISSUE TITLE
Allow underscores in Block step keys

### ISSUE THREAD

**Issue by jmendiara** [buildkite/feedback#424]
While trying to upload a `block` step in the pipeline
```yml
steps:
  - block: ":question: Fill details"
    prompt: "Fill out the details needed to continue"
    fields:
      - text: 'Platform name'
        key: 'PLATFORM_NAME'
        hint: 'The platform name'
        default: ''
```

I get the following error 

```
2018-07-17 14:11:33 WARN   POST https://agent.buildkite.com/v3/jobs/xxxxx/pipelines: 422 `key` may only contain alphanumeric characters, slashes or dashes (Attempt 1/5 Retrying in 1s)
--
  | 2018-07-17 14:11:33 ERROR  Unrecoverable error, skipping retries
  | 2018-07-17 14:11:33 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/xxxx/pipelines: 422 `key` may only contain alphanumeric characters, slashes or dashes
```

Underscores are used widely in the buildkite env vars (and in our scripts)
Having to switch to dashes `-` while dealing with metadata casues lot of mental effort to remember what word separator should use depending of truth source.

**Comment by keithpitt** [comment]
This sounds fair! I've just written up a PR internally to make this change. I'll let you know when it's on production so you can have a play!

**Comment by keithpitt** [comment]
@jmendiara I've just pushed this change out now, can you confirm that you can use underscores now?

**Comment by jmendiara** [comment]
WOOW! That 's fast! 👏 

It works! 🎉

**Comment by keithpitt** [comment]
Nice! It was an easy change :) Thanks for pointing it out!
