### ISSUE TITLE
Exposing `BUILDKITE_PARALLEL_JOB` and `BUILDKITE_PARALLEL_JOB_COUNT` in job webhooks

### ISSUE THREAD

**Issue by doodzik** [buildkite/feedback#436]
It would be nice if the` BUILDKITE_PARALLEL_JOB`, `BUILDKITE_PARALLEL_JOB_COUNT` and `BUILDKITE_LABEL` environment variable could be exposed in the job webhooks.

We are adding support for setting GitHub checks annotations from a build by creating an artifact that implements the GitHub checks annotations interface.

Our initial version mapped each job to a check run. When dealing with a parallel step this becomes a problem as the GitHub UI becomes unusable. So now we are mapping all jobs relating to a step together, but to properly summarize these we need the count of all jobs.

**Comment by keithpitt** [comment]
We shipped this today!

`parallel_group_index ` and `parallel_group_total` are both now available as attributes on all job related webhooks (also available via the REST API). We include the jobs label in webhooks - which is the same as `BUILDKITE_LABEL`.

Let me know how you go using them @doodzik!
