### ISSUE TITLE
Allow trigger steps to be skipped

### ISSUE THREAD

**Issue by nullobject** [buildkite/feedback#437]
It would be great if trigger steps could be skipped just like with command steps. i.e. Setting the `skip` value to `true` would skip that step.

Instead I get the error:

    Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/dbebef68-98b3-49ab-9cae-443cac231772/pipelines: 422 `skip` is not a valid property on the `build` configuration on a `trigger` step. Please check the documentation to get a full list of supported properties.

**Comment by keithpitt** [comment]
@nullobject it should be supported! If you pull the `skip` attribute up one level, to be this:

```
- trigger: "my-pipeline"
  skip: true
  build:
    ...
```

Then I think it should work... Based on the error you posted, I think you may have this:

```
- trigger: "my-pipeline"
  build:
    skip: true
```

**Comment by nullobject** [comment]
Ah, good catch. Sorry for the false alarm 😊
