### ISSUE TITLE
Hyperlink the pipelines under `Users > Teams > Team > Pipelines` to their equivalent pipelines

### ISSUE THREAD

**Issue by jcleal** [buildkite/feedback#439]
Hey BKers!~

From the UI, the pipelines under `Users > Teams > Team > Pipelines` (https://buildkite.com/organizations/ORG/teams/TEAM/pipelines) are not hyperlinked to their equivalent pipeline, making it super tedious to look up pipelines for a team + managing what pipelines teams have access to at scale.

I can’t tell you how many times I’ve had to manually search for a specific pipeline on the `Pipelines` page instead because I couldn’t easily go to the pipeline from the `Teams` page.

**Comment by ticky** [comment]
Hey there Jordan, I’ve just shipped a change for you which adds this!
