### ISSUE TITLE
Link to uploaded artifact

### ISSUE THREAD

**Issue by joscha** [buildkite/feedback#440]
I'd like to link to an uploaded buildkite artifact from the build log, e.g. something like:

```shell
buildkite-agent artifact upload my.log
LINK=$(buildkite-agent artifact link my.log)
echo $LINK
```
which would print something like: `https://buildkite.com/organizations/my-org/pipelines/my-build/builds/<BUILD_NUMBER>/jobs/<JOB_ID>/artifacts/<ARTIFACT_ID>`

**Comment by ewirch** [comment]
Do ANSI escape codes not work for you? https://buildkite.com/docs/pipelines/links-and-images-in-log-output

**Comment by joscha** [comment]
@ewirch are you referring to images? I would like to link the actual file, like a log file for example.

**Comment by ewirch** [comment]
I'm referring to artifact links:

> You can also link to an uploaded artifact by using the `artifact://` URL syntax

**Comment by joscha** [comment]
ah, gotcha. I think they would actually, not sure why I missed that, we use inline artifacts for images but not for files anywhere.
