### ISSUE TITLE
Display current user role in Team Members screen

### ISSUE THREAD

**Issue by davidduffett** [buildkite/feedback#448]
I found myself wondering whether or not I was a `Team Maintainer` for a particular team.  I could see that I was in the team, but the role is removed completely for the current user.

Now, you could say by virtue of the fact that I can see buttons for `Add`  and `Remove` users that I should know I'm a maintainer.  I think however for those that are prone to frequent brain-fades like me, showing the role I'm in would still be useful and save time.

![image](https://user-images.githubusercontent.com/188912/44635197-d0c55b80-a9e5-11e8-9375-ab7ce28f21cf.png)

**Comment by keithpitt** [comment]
Oh yes, this is an excellent observation! Fixed in: https://github.com/buildkite/frontend/commit/ac77c28b04dc6ac9c70e1a4a9fa62fedd7e98e23

It'll just show a static version if you don't have permission to change. Thanks for the report! 👍

**Comment by davidduffett** [comment]
Awesome - thanks @keithpitt
