### ISSUE TITLE
Separating interleaved groups

### ISSUE THREAD

**Issue by stephen** [buildkite/feedback#450]
We have some build steps that run multiple commands in parallel. It would be really neat to have a scheme for sending those outputs to separate groupings that buildkite could display, similar to [the groupings](https://buildkite.com/docs/pipelines/managing-log-output).

**Comment by ticky** [comment]
Is it possible for your parallel commands to run as separate build steps? That’s generally what we’d expect to see!

**Comment by keithpitt** [comment]
👋 I think @ticky's suggestion here is the best one! (I can imagine trying to render multiple streams of output within the one log could become quite tricky..)

I might close this one for now - but I'd love to hear any further ideas you have on it!
