### ISSUE TITLE
How do I avoid building a new artifact if only README.md has changed?

### ISSUE THREAD

**Issue by mbailey** [buildkite/feedback#452]
I'd like to exclude some directories and files from triggering the build of a new artifact that doesn't include those files.

**Comment by arturopie** [comment]
I think you need dynamic pipelines. Here is an example: https://github.com/buildkite/dynamic-pipeline-example

**Comment by ewirch** [comment]
If you know a commit does not require a build, you can tell Buildkite to skip it: https://buildkite.com/docs/pipelines/ignoring-a-commit
