### ISSUE TITLE
Pipeline env isn't set for every step using YAML syntax

### ISSUE THREAD

**Issue by jsm** [buildkite/feedback#454]
In our UI defined jobs, we can set Environment variables to be applied on every step, even with dynamic pipelines using `buildkite-agent pipeline upload`.

When switching to YAML syntax, and setting `env` at the top before the steps, they aren't passed into steps coming from dynamic pipelines using `buildkite-agent pipeline upload`.

We need a way to define environment variables we want for every step using the newer YAML syntax.

**Comment by jsm** [comment]
@lox Thoughts on this?

**Comment by keithpitt** [comment]
@jsm 👋 sorry for the late reply to this - just wanted to give a heads up that this is fixed now! 🚀

I wrote a post over in the forum with more information: https://forum.buildkite.community/t/changes-to-environment-variable-precedence/107/2
