### ISSUE TITLE
"trigger build" step type

### ISSUE THREAD

**Issue by lachie** [buildkite/feedback#46]
I'd love to be able to kick off a different build with a step, when the previous steps are all green.

I can do this by adding a script to curl the bb API in a repo, but it'd be way neater and lighter to do it right in bb. It would also not require scheduling this curl job onto an agent.

**Comment by toolmantim** [comment]
You can do this now with the `trigger` step type: https://github.com/buildkite/agent-tests/blob/master/tests/trigger-pipeline/.buildkite/pipeline.yml Docs coming soon!

**Comment by joscha** [comment]
@toolmantim [the docs](https://buildkite.com/docs/pipelines/trigger-step) say:

> Trigger steps can only be defined in your pipeline.yml file:

Does that mean I can't use this feature when dynamically generating my pipelines?

**Comment by micheletest** [comment]
We are able to have a trigger step which works in our dynamically generated pipeline.

**Comment by joscha** [comment]
Thanks @micheletest

**Comment by keithpitt** [comment]
Thanks for the feedback on this everyone! I'm gonna close this issue now since we've shipped the `trigger` step and have documentation around it.

If you've got any questions or more feedback, feel free to create a new issue! 😄
