### ISSUE TITLE
Job kill timeout should be configurable

### ISSUE THREAD

**Issue by DazWorrall** [buildkite/feedback#464]
It's currently hardcoded to 10 seconds:

https://github.com/buildkite/agent/blob/c9645249f076beef3cebce34dc9980fe8c54d502/process/process.go#L314-L319

We have some cases where it's really not unusual for a graceful shutdown to take longer than that, so it would be useful to be able to configure this - per job would be ideal, but as an agent option would be a step forward.

cc @lox

**Comment by lox** [comment]
There is an issue over at https://github.com/buildkite/agent/pull/700 with some context @DazWorrall

**Comment by DazWorrall** [comment]
Perfect, I'll subscribe to that 👍
