### ISSUE TITLE
Trigger Pull Request builds from web

### ISSUE THREAD

**Issue by moensch** [buildkite/feedback#471]
I found that I'm not able to trigger a build via web and have the following env vars set as expected:

```
BUILDKITE_PULL_REQUEST="1"
BUILDKITE_PULL_REQUEST_BASE_BRANCH="master"
BUILDKITE_PULL_REQUEST_REPO="git://github.com/org/repo.git"
```

I tried manually setting them when kicking off a build, but it seems like the agent bootstrap(?) is overriding them.

**Comment by lox** [comment]
Hmmm 🤔I thought we fixed this. @keithpitt any ideas why it's not working?

**Comment by keithpitt** [comment]
@moensch just wanted to give you a quick heads up that I've special cased those environment variables so you can manually set them via the "New Build" dialog:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/25882/48966425-2670ca80-f00c-11e8-8d01-edc502ec69ad.png">

Let me know if you have any follow up questions! 🚀
