### ISSUE TITLE
Linking to a build artifact in the log

### ISSUE THREAD

**Issue by jonleighton** [buildkite/feedback#476]
I would like the following (Ruby code) to work:

``` ruby
puts "\e]1339;url=artifact://#{path};content=#{path}\a"
```

This is correctly turned into a link in the log output, but the link points to `artifact://...`. So the artifact URL is not replaced with the real underlying URL. This happens with screenshots but doesn't appear to work with links.

Cheers!

**Comment by sj26** [comment]
Hi @jonleighton! 👋 Just wanted to let you know that this should be working now. 👌 Sorry it took so long. 🙇‍♂️

**Comment by jonleighton** [comment]
Awesome, thanks! 🎉
