### ISSUE TITLE
Support deleting logs for canceled jobs

### ISSUE THREAD

**Issue by zsims** [buildkite/feedback#480]
Per https://buildkite.com/changelog/7-delete-uploaded-job-logs it's possible to delete uploaded logs, however if the build is canceled then no "Delete Logs" button appears.

![screen shot 2018-10-30 at 2 35 45 pm](https://user-images.githubusercontent.com/1764368/47694317-4a313280-dc51-11e8-948d-baa1aeb59fb2.png)

**Comment by keithpitt** [comment]
Oh, this is a bug! On it...

**Comment by keithpitt** [comment]
@zsims fixed!

**Comment by grillp** [comment]
Serious work @keithpitt !
