### ISSUE TITLE
Allow Github Pull Request builds to be filtered based on target branches

### ISSUE THREAD

**Issue by tduffield** [buildkite/feedback#482]
For pipelines that are triggered by GitHub Pull Request events, I need the ability to filter builds by the name of the target branch. 

For example, let's say that I have two long-lived release branches in a single repo: `master` and `legacy`. Pull Requests are actively being opened against both branches, but they have entirely different pipeline requirements and are developed by separate teams. 

I want to create two pipelines, one for each release branch. I want to be able to send post commit statuses from the correct pipeline to the appropriate PR.

**Comment by moensch** [comment]
Could this be done using dynamic pipelines?

```if [[ $BUILDKITE_PULL_REQUEST_BASE_BRANCH = "legacy" ]]; then
  buildkite-agent pipeline upload .buildkite/pipeline_legacy.yml
else
  buildkite-agent pipeline upload .buildkite/pipeline_master.yml
fi
```

**Comment by tduffield** [comment]
Not in my case. Each branch is treated as an independent project, and thus gets its own pipeline.

**Comment by kerrick-lyft** [comment]
I've been corrected by my coworkers, we think that moenschs's suggestion will work for us. Will post an update once we implement it and see if things work.

**Comment by moensch** [comment]
You would still enter the appropriate branch in the branch field for what you’re building. You just enter the extra three env vars for Buildkite to recognize it as a PR build rather than just a branch build. We needed this because we have toiling that relies on the pull request number env var to be set if branch is not master.

**Comment by keithpitt** [comment]
Just wanted to let everyone know we’ve got a solution for this behind a feature flag.

If someone stumbles across this and wants access, send us an email hello@buildkite.com and we’ll flip it on for you :)
