### ISSUE TITLE
Slack notification for Unblock when I only want notifications for fail and fix after fail.

### ISSUE THREAD

**Issue by grahamegee** [buildkite/feedback#485]
I have set up my notification settings as follows:

![buildkite-notification-settings](https://user-images.githubusercontent.com/7829788/48491044-961dd300-e81e-11e8-8280-18b028119366.PNG)

Expected behaviour: I only receive notification for build failures and build passes following a build failure.

Actual behaviour: I receive an additional notification every time a build is unblocked. As shown in the image below:

![slack-notification](https://user-images.githubusercontent.com/7829788/48491233-00367800-e81f-11e8-9184-21aa090b5fdf.PNG)

**Comment by ineffyble** [comment]
I came here to report the same thing. Any chance this can be fixed?

**Comment by kimhan9** [comment]
Is there a fix?

**Comment by ticky** [comment]
This is now available!

<img width="648" alt="image" src="https://user-images.githubusercontent.com/282113/76267537-5f947480-6228-11ea-9183-433b06fc6cda.png">

For existing configurations, you will need to manually uncheck “Unblocked” or switch to “failed and fixed” which is now only those two states :)
