### ISSUE TITLE
Retry triggered pipeline step in parent build

### ISSUE THREAD

**Issue by matthewborden** [buildkite/feedback#487]
It would be awesome 💯to be able to retry a triggered build in a parent pipeline. Currently retrying the build via the retry button on the triggered build page, creates a new build that is not linked to the original parent build. It would be great to be able to retry the triggered pipeline and have the retried build be linked to the original job.

**Comment by keithpitt** [comment]
Good idea @matthewborden! I don't suppose you'd be able to copy this feedback request to our new shiny request forum over here? https://forum.buildkite.community (you'd be "first post" as well!) I've got a few q's I'd love to ask :)

**Comment by keithpitt** [comment]
(will close and continue discussion over there! 👍)
