### ISSUE TITLE
Allow to set required parameters (like in block step) for the build before it starts.

### ISSUE THREAD

**Issue by bwplotka** [buildkite/feedback#488]
Hi! :wave: 

Right now `NewBuild` UI allows to set name, commit, branch, and initial ENV_VARS. This means that there is no way to parametrize build with more human readable options like it is nicely available with https://buildkite.com/docs/pipelines/block-step.

The problem with using `build step` is that even when you put it at the very top step and start a Build - you need to wait from 5s to sometimes a couple of minutes for the environment to set up (e.g github repo being pulled) until you can pass parameters. 

For a fully automated pipeline, you don't wont to require the user to watch build status closely until it can provide actual info. Especially when the idea is to provide _initial_ input only to limit user context switching.

So acceptance criteria for this would be:
-  Be able to set required parameters for the build before it starts.

Also the color of status for "blocked/paused" build is really similar to green one which could be confusing, but that's a separate issue.

Am I missing any obvious solution here? (:

**Comment by jmendiara** [comment]
Same than #429 i guess

**Comment by keithpitt** [comment]
@bwplotka 👋 howdy! No, you're not missing anything! I think I can help you out here...

Would you mind copying this over to our new forum here? https://forum.buildkite.community/c/support I'll get some more info from you there and we'll figure something out!

(will close for now, and we'll continue chatting over there!)
