### ISSUE TITLE
build-only script user (or api token)

### ISSUE THREAD

**Issue by lachie** [buildkite/feedback#49]
I'd like to have a build-only user whose api token could be used from scripts.

Actually our ideal would be to have something like flowdock where each flow has a token which you can use with the api to post messages. So each project would have a token which could be used to trigger a build.

Closer to your current setup, I'd like to have a user who doesn't count against the user count, who can only trigger builds.

Currently we have to scatter our own user tokens about the place which isn't great, especially for revocation.

**Comment by keithpitt** [comment]
Our new API Access Tokens should help here! https://buildkite.com/blog/api-access-tokens :dancers:
