### ISSUE TITLE
Retry builds when agent went away; code -1

### ISSUE THREAD

**Issue by prestonvanloon** [buildkite/feedback#491]
Is there any way for buildkite to retry a build when the agent dies or disappears?

**Comment by silvamerica** [comment]
That should be possible: https://building.buildkite.com/new-in-buildkite-job-retries-3f60a8d45ed2

**Comment by lox** [comment]
Yup our intent is that automatic retries will sort this out!

**Comment by prestonvanloon** [comment]
Thanks! I've switched over to the yaml config rather than the really nice UI :( and now I can add that option.
