### ISSUE TITLE
Parallel steps with parallelism=1 should not show as parallel

### ISSUE THREAD

**Issue by joscha** [buildkite/feedback#493]
We auto-generate our buildkite pipelines dynamically and some steps have `parallelism: 1` where the number is determined automatically.

Since https://buildkite.com/changelog/42-parallel-jobs-now-show-as-a-single-group these show like:

![web__build_editor__36004](https://user-images.githubusercontent.com/188038/51158598-55ebd700-18d9-11e9-8e88-7067b8ccc8a8.png)

It would be great if `parallelism: 1` would just show like any other non-parallel step.

**Comment by ticky** [comment]
Hah! Good catch 😅

**Comment by joscha** [comment]
Not a biggie but related: 
![web__build_editor__36107](https://user-images.githubusercontent.com/188038/51162003-b8000880-18e8-11e9-9b3b-0481ab792d5f.png)

(the overview step seems to acquire the number of the first run for `%n`)
