### ISSUE TITLE
Github style accounts

### ISSUE THREAD

**Issue by nhooyr** [buildkite/feedback#494]
I use my private email with git even on my company's repos cause as its a pain to have to switch emails and make sure I'm using the right one every time I commit. However, I'd also like to have a personal Buildkite account not linked to my company's account with my personal email. I think it'd be best if Buildkite's accounts worked like Github's where you had a single account linked to your email that could be invited to organizations.

As a workaround, I am using  https://stackoverflow.com/questions/34597186/use-a-different-user-email-and-user-name-for-git-config-based-upon-remote-clone now to automatically switch between my work and private email.

**Comment by matthewd** [comment]
Hey @nhooyr!

>  I think it'd be best if Buildkite's accounts worked like Github's where you had a single account linked to your email that could be invited to organizations.

Conveniently, that's exactly how Buildkite accounts work! :smile:

If you click on the organization switcher (top left, next to the Buildkite logo), you should see the option to create a new organization.

Drop us an email at support@buildkite.com if you need any help getting it sorted out.

**Comment by nhooyr** [comment]
Awesome thanks.
