### ISSUE TITLE
links should be recognized and clickable in buildkite logs

### ISSUE THREAD

**Issue by nhooyr** [buildkite/feedback#496]
If a CI job wants to link you to something, would be nice UX if you could just click on it versus highlighting and copy paste or right click  and `go to`.

**Comment by ticky** [comment]
You can create clickable links in Build output, but you have to be explicit about it: we support the same syntax as iTerm 2 and other terminals with link support. An example script for outputting a link can be found here: https://github.com/buildkite/terminal-to-html/blob/bc7274cbce9fb5c752c32fdb4ea267cb4260417f/link.sh

**Comment by nhooyr** [comment]
@ticky is this documented anywhere?

**Comment by ticky** [comment]
Not nearly as well as it should be 😉 it’s in the docs for the underlying tool, but not in our product docs. We [mention embedding images](https://buildkite.com/docs/pipelines/images-in-log-output), but not links. I’ve opened buildkite/docs#412 for adding it!
