### ISSUE TITLE
[BB] "Branch Limiting" not working

### ISSUE THREAD

**Issue by harryi3t** [buildkite/feedback#501]
I have put `!develop` in the branch limiting section, still whenever a pull request is merged to develop branch, the pipeline is triggered

![image](https://user-images.githubusercontent.com/5207331/53144570-cb2a8600-35c2-11e9-8d60-f618760da8a3.png)

**Comment by toolmantim** [comment]
Sorry you’re experiencing that @harryi3t — could you email support@buildkite.com with links to the build and pipeline, and we’ll look into what’s happening there.
