### ISSUE TITLE
Ask: tidier copy/paste result when copying from the build log

### ISSUE THREAD

**Issue by jgehrcke** [buildkite/feedback#525]
We love the build log view, it's visually appealing. Often times we of course have to copy and paste some snippets from it. Say, I copy these four lines:
![Screenshot from 2020-07-24 17-28-32](https://user-images.githubusercontent.com/265630/88407945-2a518300-cdd3-11ea-908c-993135257755.png)
(this is a screenshot from the buildkite build log view, really, and the blue means that I have selected these lines).

When I then paste these lines what I get is:

```
[2020-07-24T12:13:20Z] rsync -avr \
--
  | [2020-07-24T12:13:20Z] 	--exclude='*node_modules*' \
  | [2020-07-24T12:13:20Z] 	--exclude='.npm' \
  | [2020-07-24T12:13:20Z] 	--exclude='.node-version' \
```
I (we) chose not to care for a year. But honestly, this is pretty annoying:
- the way the first line differs from the rest of the lines in terms of prefix
- the way how the result is 5 lines instead of 4, because a magic second line with `--` was invented :-)

Is there maybe an easy way to change the method this log is presented in the browser's DOM so that the paste result would represent the text _verbatim_?

Thanks!

**Comment by jgehrcke** [comment]
Ha. When choosing "paste as plain text' (or ctrl+shift+v in my browser) indeed the result is as expected:
```
[2020-07-24T12:13:20Z] rsync -avr \
[2020-07-24T12:13:20Z] 	--exclude='*node_modules*' \
[2020-07-24T12:13:20Z] 	--exclude='.npm' \
[2020-07-24T12:13:20Z] 	--exclude='.node-version' \
```
Sorry for the noise!

**Comment by ticky** [comment]
I’m with you @jgehrcke - I think browsers are trying to be a little too clever; we currently present job logs in a table, and it tries to put a separator between table columns even though there’s only one you can select. I’m hoping we can improve the default behaviour in a future update, but for now you have indeed found the workaround I’d have suggested! 👍🏼
