### ISSUE TITLE
Trigger build commit defaults to master

### ISSUE THREAD

**Issue by cirode** [buildkite/feedback#53]
When you trigger a build the commit box defaults to "master"

This then triggers the agent to do a git checkout -qf "master", which ( only ocassionally mind.. which is odd ) checks out the master branch, thus ignoring the branch setting supplied

The default for the commit should be HEAD

**Comment by keithpitt** [comment]
We now default the commit box to `HEAD`, so it should solve most of these problems. We also send the commit back to buildkite after the first step has run, and subsequent steps will use the actual commit, instead of head. :dart:
