### ISSUE TITLE
Are you sure you want to continue connecting (yes/no)?

### ISSUE THREAD

**Issue by joshuapaling** [buildkite/feedback#57]
When I first set up my project and it's doing the initial `git clone`, I get:

```
The authenticity of host 'bitbucket.org (131.103.20.168)' can't be established.
RSA key fingerprint is 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40.
Are you sure you want to continue connecting (yes/no)?
```

Of course, I can't give a 'yes' through the buildbox interface.

So, I log in manually and clone, say yes, cancel the clone, then run my build. It works fine.

But in the default `bootstrap.sh`, would it be better to do something like:

`yes | buildbox-run "git clone "$BUILDBOX_REPO" . -qv"`

instead of:

`buildbox-run "git clone "$BUILDBOX_REPO" . -qv"`

So it automatically answers yes and that extra manual step isn't needed?

**Comment by GodQ** [comment]
echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/config
and all fixed

**Comment by Esqarrouth** [comment]
> StrictHostKeyChecking no

is that secure?
