### ISSUE TITLE
Mismatch between docs and api call results for the agents api call

### ISSUE THREAD

**Issue by andrewjhumphrey** [buildkite/feedback#65]
The docs for the agents api call suggest they will return a state attribute that tracks whether the agent is busy with a job or not.  (https://buildbox.io/docs/api/agents)

The results from the api call

curl "https://api.buildbox.io/v1/accounts/envato-marketplaces/agents?api_key=[SNIP]

  {
    "id": "f8fb9e58-02a7-4751-92ea-fbd9a3bb5c86",
    "url": "https://api.buildbox.io/v1/accounts/envato-marketplaces/agents/[SNIP]",
    "name": "unavailable",
    "connection_state": "disconnected",
    "ip_address": "[SNIP]",
    "access_token": "[SNIP]",
    "hostname": "ip-10-0-0-123",
    "user_agent": "buildbox-agent/1.0-beta.2 (linux; amd64)",
    "creator": null,
    "created_at": "2014-10-09 22:27:24 UTC"
  }

Don't include the state attribute, it would be nice if it did.

The problem I'm trying to solve is to use the state of the agents to make a decision about autoscaling the number of agents.

**Comment by toolmantim** [comment]
This is all up to date now :)
