### ISSUE TITLE
Mismatch between JSON structures of different job types

### ISSUE THREAD

**Issue by bwilkins** [buildkite/feedback#66]
I've noticed that some job types (waiter, manual) have totally different structure, and this is obviously because they are inherently different from the other job types. The problem this causes, however, is that it prevents the ease of filtering by attribute, as suddenly we have to check for the presence of the attribute required (depending on how you're processing the data of course).

**Comment by keithpitt** [comment]
@bwilkins unfortunately that's be design. A `waiter` step type doesn't have agents, so it'd be weird to include those keys - and if we did - we'd have to default them to something that may be lies. Perhaps when we start looking at `v2` of the API - we'll be able to clean this up a little. Thanks for the feedback though! :heart:
