### ISSUE TITLE
Having a different colouration for "Waiting for manual input" builds

### ISSUE THREAD

**Issue by cirode** [buildkite/feedback#68]
When Pipeline Builds have reached an impass with a "Click to unlock" step, they currently show up as "Finished / Successful"

This is not strictly true, they are waiting on user input. It would be great to know which builds are waiting for user input vs successful

may I suggest Puce? or Metallic Bronze?

**Comment by keithpitt** [comment]
@cirode it took a few years, but we finally have an icon for "Waiting for manual input"! https://buildkite.com/changelog/19-blocked-builds
