### ISSUE TITLE
Get build artifact URLs through API

### ISSUE THREAD

**Issue by tazjin** [buildkite/feedback#69]
Would be awesome to get the URLs of build artifacts through the normal API. At the moment I'm doing this by first fetching the build ID and then querying the agent API, which is less than optimal.

(In the meantime, if anyone finds this via Google: [This](https://gist.github.com/tazjin/141b5ebffc0b6e3dd621) is my workaround)

**Comment by mcgain** [comment]
:+1:

**Comment by keithpitt** [comment]
This is now possible! :dancers: https://buildkite.com/docs/api/artifacts#download-an-artifact

**Comment by keithpitt** [comment]
Thanks again for the suggestion @tazjin, and sorry it took so long getting back to you!!
