### ISSUE TITLE
Link to a particular line in the output

### ISSUE THREAD

**Issue by mtibben** [buildkite/feedback#70]
If there's long output, and you need to send a link to someone, it would be great to be able to click that line, get the anchor URL from the browser URL and send it off - same way that github does with diffs

**Comment by keithpitt** [comment]
Hey @mtibben - we're very close to releasing this. Watch this space :)

**Comment by mtibben** [comment]
Nice!

**Comment by keithpitt** [comment]
We shipped build lines along with https://buildkite.com/blog/animated-gifs-in-your-log-output :dancers: Thanks for the idea @mtibben!
