### ISSUE TITLE
Ability to disable concurrent builds of a project

### ISSUE THREAD

**Issue by psynix** [buildkite/feedback#72]
One of our projects pushes to our internal docker registry. Having two steps in separate builds attempting to push to the same repository will cause one of them to fail.

Being able to disable concurrent builds would fix this.

**Comment by keithpitt** [comment]
We've launched a `concurrency` option for jobs, so if you change it to 1, only 1 type of that job can run at once. Thanks for the feedback! :dancers:

**Comment by pda** [comment]
Nice, thanks :rocket:

**Comment by psynix** [comment]
Thanks guys.
