### ISSUE TITLE
Occasional Freezing of the Build Pipeline

### ISSUE THREAD

**Issue by cirode** [buildkite/feedback#76]
https://www.dropbox.com/s/luc0d5za3xc7bqd/Screenshot%202014-11-19%2017.11.32.png?dl=0

Occasionally we get a situation where all steps before a checkpoint have been actioned, however the steps after the checkpoint never get assigned

The build then waits indefinitely for completion.. which never occurs

The above screenshot shows this occuring

NOTE: There were many available agents at the time this was taken

**Comment by keithpitt** [comment]
I think most of these problems have been squished now :dancers:
