### ISSUE TITLE
Please add a way to manually delete/time out elastic agents

### ISSUE THREAD

**Issue by lachie** [buildkite/feedback#78]
I'd like a way to preempt the timing out of an already-dead agent.

Here's the scenario
* Agent dies ungracefully (natural causes / OOMface killah / kill -9) and doesn't have a chance to tell BB its shuffling off
* Agent hangs around in the interface and in the available-agent pool for like ever.
* Jobs get assigned to non-existent agent.
* _Nothing happens_
* Agent times out... job fails? Gets reallocated? Who even has time to find out?

(I've just run across it, and Andy Snow saw this happen at Railscamp during presales ;)

**Comment by keithpitt** [comment]
You can now manually turn off agents:

![image](https://cloud.githubusercontent.com/assets/25882/6736221/69bfa134-ce5b-11e4-879c-bd6575a24dfe.png)

We're also working on a more aggressive timeout - but this should help for now.
