### ISSUE TITLE
Feature Request: Line timestamps

### ISSUE THREAD

**Issue by Vektah** [buildkite/feedback#80]
One of the few features I miss from Jenkins was from a plugin https://wiki.jenkins-ci.org/display/JENKINS/Timestamper.

It prefixes to every line in the build output with a timestamp showing when that line was emitted. This helps to track down what in a build is running slowly. It was configurable to show time since build start (this was arguably most useful) or local timestamps.

**Comment by keithpitt** [comment]
We've got something in the works that should give you this behaviour back @Vektah - watch this space :)

**Comment by keithpitt** [comment]
@Vektah if you upgrade to our latest agents, you'll now see group timing in the build output. Thanks for the idea!! :heart:

**Comment by nello** [comment]
Closing this issue was, in fact, a lie. Group timing is not the same thing as line timing. 

Let's just say that (like everyone in the entire world) I want to figure out which exact part of my build is the slowest. If I use Jenkins I can see precisely how long every single piece of my build takes. With BuildKite, this is apparently reaching for the moon.

**Comment by toolmantim** [comment]
@nello it wasn't meant as a lie at all. This is something we'd love to add, we just don't have it available yet. Group timings were first off the rank, and allowed us to show a bar graph in the right hand side of the header column too. I'll simply reopen this ticket and close the other as a dupe, as I'm sure @Vektah probably wants to stay in the loop too.

**Comment by nello** [comment]
Thanks Tim. Unnecessary grumpy on my behalf, but a pet peeve when people close issues that aren't really resolved.

Cheers for the update,
Nello

**Comment by toolmantim** [comment]
No sweat @nello

**Comment by Finchster** [comment]
+1

**Comment by krutisfood** [comment]
👍

**Comment by anthcourtney** [comment]
+1

**Comment by samjeffress** [comment]
+1

**Comment by Vektah** [comment]
I hate to be *that guy* but can we :+1: on the ticket, rather than in a message? Everyone gets an email...

**Comment by keithpitt** [comment]
We've shipped this in v2.4 of the agent! If you run the agent with `--timestamp-lines` you'll see timestamps at the beginning of each log line. Thanks @stefanmb!

**Comment by nello** [comment]
Thanks guys!
