### ISSUE TITLE
Mention User in HipChat Notification

### ISSUE THREAD

**Issue by camhine** [buildkite/feedback#85]
Really happy using buildkite so far. Keep up the good work.

We have our builds hooked up to a room in HipChat. It would be awesome if these notifications could mention the responsible party when they hit the room. That way the user is notified directly when they break the build.

Example:

[Still Failing] A project (branch) #20: Commit message

Could be:

[Still Failing] A project (branch) #20: Commit message @camhine

**Comment by keithpitt** [comment]
@camhine yeah! We could probably do this. Tricky bit there is mapping Buildkite users to HipChat users, but we've got some ideas on how to do that as well.

**Comment by therealbnut** [comment]
:+1:

We wrote a script to do this for our build, and had the same issue with mapping usernames. We haven't done this part yet but were thinking you may be able to do it by correlating the git email address to the hipchat one:

    https://www.hipchat.com/docs/api/method/users/list

    git config user.email

**Comment by keithpitt** [comment]
@therealbnut that's an interesting idea! Correlating is an interesting idea, and we may be able to attempt that as a default if the user hasn't manually entered a username. We've got some changes planned for our HipChat integration in a few weeks, so stay tuned!

**Comment by keithpitt** [comment]
Howdy! I just pushed a change to HipChat notifications, so they'll now include the Buildkite user that triggered the build - it's not the HipChat user name, but I think it's pretty close :) Sorry this open for so long!

**Comment by camhine** [comment]
Awesome! I can see that our notifications have names against them now :)
