### ISSUE TITLE
Ability to re-run a job in a pipeline

### ISSUE THREAD

**Issue by toolmantim** [buildkite/feedback#86]
"Would be handy to be able to repeat only one step in pipeline instead of the whole build. For example, I have 3 steps in my pipeline and last step builds docker image. If build of image fails I need to rerun the whole pipeline even if sometimes it fails due to environment/agent issues. Especially, useful for long pipelines." via @Maxim-Filimonov

**Comment by adriancb** [comment]
:+1:

**Comment by tommeier** [comment]
:+1:

**Comment by colinbankier** [comment]
:+1:

**Comment by keithpitt** [comment]
I think I've got an idea on how this can all work in my head now. Stay tuned!

**Comment by nikyoudale** [comment]
+1

**Comment by kouky** [comment]
:+1:

**Comment by tommeier** [comment]
:+1:

**Comment by hearnden** [comment]
+1, if this means resuming the full pipeline from an intermediate job, rather than running a single job in isolation without its subsequent jobs.

**Comment by keithpitt** [comment]
:+1:

**Comment by toolmantim** [comment]
:+1:

**Comment by DamonOehlman** [comment]
![](http://i.giphy.com/OE6FE4GZF78nm.gif)

**Comment by mtcmorris** [comment]
![ok_daft_punk](https://cloud.githubusercontent.com/assets/142934/10505766/a645e536-735c-11e5-9bbb-bbc03eb43d83.gif)

**Comment by nullobject** [comment]
:+1:

**Comment by plasticine** [comment]
![conbats](https://cloud.githubusercontent.com/assets/18076/10505870/7a23814c-735d-11e5-973b-45ed3b1f6608.gif)

**Comment by chaitanyakuber** [comment]
:+1:

**Comment by SomeoneWeird** [comment]
![3847f580-51a5-0132-0b47-0eae5eefacd9 0 0](https://cloud.githubusercontent.com/assets/665754/10835597/8145178c-7ef8-11e5-9b12-862fda164264.png)

:+1:

**Comment by tigris** [comment]
![yes](http://replygif.net/i/241.gif)

**Comment by alexjurkiewicz** [comment]
![yes](https://cloud.githubusercontent.com/assets/379509/10835983/7edbeee0-7efc-11e5-9318-e33c180fc7c1.gif)

**Comment by keithpitt** [comment]
:soon:

**Comment by keithpitt** [comment]
![image](https://cloud.githubusercontent.com/assets/25882/12768790/5b723ba2-ca66-11e5-9e70-fd96ac970bf9.png)

**Comment by tommeier** [comment]
[YES](http://i.giphy.com/12Rq9uCNxcxtjq.gif)

**Comment by nikyoudale** [comment]
\o/

**Comment by alexjurkiewicz** [comment]
Omg!

**Comment by keithpitt** [comment]
It's shipped! If a job fails you'll see a new "Retry" button next to the tabs. If you hit that, it'll clear the job log and artifacts, and run it again. :dancers:

**Comment by nocache** [comment]
Great work 'kiters! This is awesome!

**Comment by keithpitt** [comment]
@nocache <3
