### ISSUE TITLE
ability to disable building particular commit

### ISSUE THREAD

**Issue by lekki** [buildkite/feedback#87]
Hey,

I can't find any info about it. Can you please advice if it's possible to disable building a git commit by specifying a tag for example [ci skip] similar to other ci's like travis? (http://docs.travis-ci.com/user/how-to-skip-a-build/)

thanks
Pawel

**Comment by keithpitt** [comment]
@lekki hey! You sure can! Check this out: https://buildkite.com/docs/guides/skipping-a-build

**Comment by lekki** [comment]
Thanks @keithpitt , you guys rock!

**Comment by keithpitt** [comment]
:heart:
