### ISSUE TITLE
UI broken on Yosemite Chrome 41.X

### ISSUE THREAD

**Issue by lekki** [buildkite/feedback#88]
Hey,

Not sure if it's a coincidence but since yesterday after Chrome update to ver 41.X  the web ui looks like this:
http://cl.ly/image/1O0r0u293L0n

Regards,
Pawel

**Comment by keithpitt** [comment]
@lekki that doesn't look right at all! Could you email hello@buildkite.com the link to the build in question so we can take a look!

**Comment by keithpitt** [comment]
This is fixed now! :dancers:
