### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by robmonie** [buildkite/feedback#92]
We've been noticing some pretty laggy performance in the web ui on and off over the last while (few weeks maybe). By laggy, I mean regularly up to 10 seconds to render a page. This doesn't seem to be limited to any particular page. Anything from listing projects to specific builds.

Interestingly this is never reflected on the buildkite status page.

-rob

**Comment by keithpitt** [comment]
Hey @robmonie - just wanted to give you an update on how we're progressing getting things speedy again. Just posting it here as well so everyone can see.

One of the biggest problems was how logs were streamed to Buildkite. The entire log was sent every second, and when a job log gets around 30-40mb, that's alot of data hitting the Buildkite servers at once. This has taken down our servers a couple of times. In the latest agent beta, we've fixed this by chunking the log into smaller bits and streaming them to our servers. This has helped a lot. So as more customers upgrade to the new agents, the faster we'll get. I know Hooroo have already upgraded.

We've rolled out internally a different mechanism of log storage, so retrieving logs should be less stress on our servers and much faster on the front end.

We've added a ton of monitoring around how many 502's we're sending out, and keeping a real close eye on those numbers. 502's were one of our biggest pain points, and we've doubled the amount of servers we have. We've also added monitoring around our RDS instances so we can track the performance of that.

New Relic has been super useful in finding our slow spots, and we've been optimising everything we can.  The cruise control endpoint (cc.xml) has been another slow spot, and we've made changes to that as well.

We also found some massive memory leaks within our application - to the point where we were leaking gigabytes. All those have been fixed and plugged. Hopefully we'll blog about our findings and how we fixed them soon!

All of the optimisations we've been making are all dropping today + over the next few days, so hopefully you should notice a nice speed boost.

**Comment by robmonie** [comment]
Nice summary. Thanks for the update.

**Comment by keithpitt** [comment]
Just one last update on this, we've upgraded our database over the weekend, and most of our response times have been pretty good over the last few weeks. Im going to close this issue for now since I haven't seen any slow response times in New Relic. If you start seeing things getting slow again, feel free to re-open! Thanks for your patience with this :heart:
