### ISSUE TITLE
Feature request: Gap-less pagination.

### ISSUE THREAD

**Issue by byroot** [buildkite/feedback#93]
It would be handy if the pagination links were based on the last seen record instead of page numbers.

Example:

```
GET https://api.buildkite.com/v1/organizations/my-shiny-org/agents?since=0b461f65-e7be-4c80-888a-ef11d81fd971
```

That would give us the guarantee that we are not skipping an agent because another process shifted them all by deleting the first one.

Obviously that implies that there is a default ordering to the list.

Thanks!

**Comment by keithpitt** [comment]
👋 2 years later! We pushed out gapless pagination to our GraphQL API. It uses `cursor` based pagination so you shouldn't ever miss anything :)
