### ISSUE TITLE
Feature request: show an agent's current and historical builds

### ISSUE THREAD

**Issue by simpsora** [buildkite/feedback#94]
On the agent info page (`/agents/.../edit`), it would be super helpful to see both currently-running jobs and the last few jobs run there.
- Use case: see what job is running on this agent right now
- Use case: see historical trend (build completion status, build time) to see if an agent is "sick"

This would be tremendously helpful to understand if a new agent is working as intended or not.

Cheers!

**Comment by stajs** [comment]
+1

**Comment by ticky** [comment]
Closing in favour of #387
