### ISSUE TITLE
Feature Request: Allow interpreted user-defined project variables

### ISSUE THREAD

**Issue by vacri** [buildkite/feedback#95]
This would allow user-defined environment variables to reference system-defined env vars. Currently the user-defined project vars are literal strings, not interpreted ones.

For example, I have a buildplan that reuses the same tag for a docker build in multiple steps. I'd like to simplify it to a single short var to make the commands for each buildstep easier to read. The tag I wanted to use would be built out of the pre-existing system vars:

```
BUILDTAG="${BUILDKITE_BRANCH}-b$BUILDKITE_BUILD_NUMBER"
```

At the moment, this gives me the literal string. I was expecting shell convention of double quotes = interpreted string.

In slack chat, Tim mentioned that literal strings were currently intended design (example use case: AMOUNT=$5), but suggested perhaps that if double quotes were detected, to then interpret the string. If no quotes or single quotes, use the literal string.

**Comment by keithpitt** [comment]
If you're doing: `AMOUNT=$5` - we could always just support: "AMOUNT=\$5" - I think escaping may be easier instead of quote handling - but I can look into it!

**Comment by keithpitt** [comment]
👋 v3 of the `buildkite-agent` does environment variable interpolation which handles most of this! Sorry it took so long for us to close this issue!
