### ISSUE TITLE
[Mobile safari bug][iOS] Unable to expand build step subheading, only via mini step button

### ISSUE THREAD

**Issue by tommeier** [buildkite/feedback#96]
Minor irritant, on iOS Safari, when viewing a build, clicking a build step group header, it won't expand, but it *will* expand if you click the mini step:

![screen shot 2015-05-17 at 9 57 14 am](https://cloud.githubusercontent.com/assets/19973/7668419/3711d484-fc7b-11e4-9f13-6de0dddb485a.png)

Workaround exists.

**Comment by keithpitt** [comment]
All fixed!! :dancers:

**Comment by tommeier** [comment]
:clap: :clap: Thanks!
