### ISSUE TITLE
[Feature request] Optional build step type

### ISSUE THREAD

**Issue by tommeier** [buildkite/feedback#97]
Right now we can create a build pipeline step that either always runs, or runs after a 'lock' step.

Would love some optional 'only on click' step option.

User case: We have a long running script for capturing the UI across 5 devices and their varios iOS combinations throughout the app. I don't necessarily want to run only on a particular branch, or all the time. I'd like the ability to just click a button and trigger it if we wanted the artefacts generated.

**Comment by keithpitt** [comment]
Hrm, could you create a new project with just 1 build step that did that?

**Comment by keithpitt** [comment]
(Just thinking out loud :smile:)

**Comment by tommeier** [comment]
Yup, totally could as a workaround, it would just be nice to keep it all together, as an optional additonal build artefact, say for the release branches and so forth. Or to go back and generate UI for a past build in that time, for instance.

**Comment by keithpitt** [comment]
:wave: Sorry it took so long to respond! I think with a combination of a dynamic pipeline, and a `block` step with prompts - this is now totally possible!
