### ISSUE TITLE
Disable builds on git tags

### ISSUE THREAD

**Issue by avaly** [buildkite/feedback#98]
We use git tags to mark what versions have been deployed to our staging/production environments. It seems BuildKite executes separate builds for those git tags.

It would be nice if there was an option to disable builds on git tags, since they don't do anything useful for us.

**Comment by keithpitt** [comment]
Hi @avaly - yeah it's something we want to add. In the mean time, if your tags have a common pattern: "release-1234" or something, you can filter add a branch filter like: "!release-*" and it won't build any branch/tags that have that format: https://buildkite.com/docs/guides/branch-configuration

**Comment by sebglazebrook** [comment]
+1 to get this one sorted.

It's kinda confusing how buildkite treats tags as branches.

Also if your build tags your a commit and the tag generates a build which then tags, which then builds, which then tags, which then builds etc

**Comment by sebglazebrook** [comment]
@keithpitt ^^

**Comment by keithpitt** [comment]
Ah yeah, we gotta do this. I'll schedule it in for this week.

**Comment by sjparkinson** [comment]
Heya any update on this feature?

We're using semver at @graze for a few projects, but trying to filter branches with `*.*.*` doesn't seem to work. It'd be great to define tag only steps.

**Comment by mkllnk** [comment]
This would be great. We just ran into the same problem. We are using a variable `$BUILDKITE_BRANCH` in some `git branch` commands which fail with the name of a tag. Furthermore, why run the build again if the same commit has been run already?

**Comment by keithpitt** [comment]
Hey all! Finally got this change into production!

![image](https://cloud.githubusercontent.com/assets/25882/10220451/3f8e108e-680d-11e5-8d3c-b0e7ba7adf7e.png)

If you go to your project settings page, and scroll down to the "Github" or "Bitbucket" section, you'll see a new "Build tags" option.

Thanks for being so patient! Let me know how it goes for you! :dancers: :dango:

**Comment by sebglazebrook** [comment]
@keithpitt 

I tried to activate this on a build and it's still building off tags. I disabled the "Build tags" checkbox but it doesn't seem to have done anything.

**Comment by keithpitt** [comment]
@sebglazebrook hrm, that's not good! Could you email keith@buildkite.com with the links to the builds and the project that's having issues? I'll look at it right away for you.
